### ISSUE TITLE
Cannot allocate memory in alsa

### ISSUE THREAD

**Issue by aajjbb** [copycat-killer/lain#100]
Hi, today I stumbled with a probable memory leak from alsa widget: 
"~/.config/awesome/lain/widgets/alsa.lua:32 amixer -M get Master: Cannot allocate memory"

I don't know much about alsa, so, is it an alsa issue or lain has something to do with ?

Thanks in advance.

**Comment by copycat-killer** [comment]
The widget just spawn alsa in the simplest way, I'd be surprised if this causes you the leak.

Try investigating on alsa and your average memory usage.

**Comment by copycat-killer** [comment]
So?

**Comment by aajjbb** [comment]
Apparenty it didn't happen again. I guess it was some internal issue that ended up reflecting the alsa widget behaviour. 
Thank you.
