### ISSUE TITLE
net widget: failing iface autodetection

### ISSUE THREAD

**Issue by vojinc** [copycat-killer/lain#102]
Hello everyone.I have a problem with lain widget net.lua.I use a powerarrow-darker in my Slackware linux on laptop.Everything work without a problem,my wifi eth work but widget for download and uploud don't work.When i start my OS first on screen show icon no_net.png.Please help me.Thank you for a cooperation.

**Comment by copycat-killer** [comment]
If you are sure you have an active network device, then the widget i faliing to autodetect it.

But you can set it manually.

Execute the following command:

```shell
ip link show
```

the device which state is **UP** is the one you have to manually set as `iface` in the net widget, like this:

```lua
-- Net
neticon = wibox.widget.imagebox(beautiful.widget_net)
neticon:buttons(awful.util.table.join(awful.button({ }, 1, function () awful.util.spawn_with_shell(iptraf) end)))
netwidget = lain.widgets.net({
    iface = "your UP device", -- set it here
    settings = function()
        widget:set_markup(markup("#7AC82E", " " .. net_now.received)
                          .. " " ..
                          markup("#46A8C3", " " .. net_now.sent .. " "))
    end
})
```

**Comment by vojinc** [comment]
Thank you very much ,it`s work.Great

**Comment by Incognito4nonymous** [comment]
Hello ! It is I again, I'll just drop this here, to make it work, simply change that line : 
`local function worker(args)
    local net = { last_t = 0, last_r = 0, devices = {} }

    function net.get_first_device()
        local ws = helpers.read_pipe("ip link show | cut -d' ' -f2,9")
        ws = ws:match("%w+: UP") or ws:match("ppp%w+: UNKNOWN")
        if ws then return { ws:match("(%w+):") }
        else return {} end`
Into 
`local function worker(args)
    local net = { last_t = 0, last_r = 0, devices = {} }

    function net.get_first_device()
        local ws = helpers.read_pipe("/usr/sbin/ip link show | cut -d' ' -f2,9")
        ws = ws:match("%w+: UP") or ws:match("ppp%w+: UNKNOWN")
        if ws then return { ws:match("(%w+):") }
        else return {} end`
Well if it doesn't for you, I guess you can simply fall back into the manual method.
Cheers !

**Comment by copycat-killer** [comment]
Just `/usr/bin` is working too?

**Comment by Incognito4nonymous** [comment]
Negative, I bet it is because it is intended to be ran with elevated privileges, which is why it is in the /usr/sbin folder.
Still under Slackware by the way :smile:

**Comment by copycat-killer** [comment]
Maybe you are not a sudoer?

**Comment by Incognito4nonymous** [comment]
I don't use sudo at all, I'm using "su-c" when I need elevated privileges, old school mode.

**Comment by copycat-killer** [comment]
That's the explanation then.

I've never met a `su` purist before, probably because `sudo` is a safe alternative since 1986.

I'll switch to `/usr/sbin`.

**Comment by paescuj** [comment]
Now, it doesn't work anymore under Gentoo, because the binary is located at `/bin/ip`. I think we need another solution here, since there seems to be a inconsistency with the location between linux distributions.

**Comment by Incognito4nonymous** [comment]
Well, I think most Slackware users are Su purists since sudo is a pain in the ass to configure properly on that distribution.

And about the location varying, it is indeed a problem, perhaps a script to detect the location of the executable should be created with `wereis` or something like that, after all the iface detection in the net widget is pretty much using the same technique. 
I also had the same problem with the Bat widget and with the Temp one, the input file location is varying...
Or to keep it simple and stupid, just a Wiki entry to explain how to modify the files in order to make them work. :wink:

**Comment by copycat-killer** [comment]
The autodetection function is just a simple plus and I don't want to bloat it.

I revert to previous status.

**Comment by Incognito4nonymous** [comment]
Okay, at least that page will help anyone having this problem.

**Comment by paescuj** [comment]
> The autodetection function is just a simple plus and I don't want to bloat it.

I quite agree.

> I revert to previous status.

Thanks!
