### ISSUE TITLE
Can't create more than one fs widget.

### ISSUE THREAD

**Issue by marcoamorales** [copycat-killer/lain#103]
```
attempt to call fields 'fs' (a table value)
```

This is the error that I get whenever I try to do something like this:

```
fsslash = lain.widgets.fs({
    partition="/",
    settings  = function()
        widget:set_markup(markup("#80d9d8", "/ " .. fs_now.used .. "% "))
    end
})

fshome = lain.widgets.fs({
    partition="/home",
    settings  = function()
        widget:set_markup(markup("#80d9d8", "/home " .. fs_now.used .. "% "))
    end
})
```

If I comment out one of those two ( doesn't matter which one, I tried both ) the code works. And yes I'm adding the widgets to the menu and removing/renaming whenever testing one or another.

**Comment by copycat-killer** [comment]
Update to  adc899b and use this widget:

```lua
fsroothome = lain.widgets.fs({
    partition="/",
    settings  = function()
        home_used = tonumber(fs_info["/home used_p"]) or 0
        widget:set_markup(markup("#80d9d8", "/ " .. fs_now.used .. "% ")
        .. markup("#80d9d8", "/home " .. home_used .. "% "))
    end
})
```
[Wiki updated.](https://github.com/copycat-killer/lain/wiki/fs)

If this satisfies you, close the issue yourself.

**Comment by copycat-killer** [comment]
I think the request is satisfied, but report here if you need.

Closing.

**Comment by marcoamorales** [comment]
Sorry, hadn't been able to test this. It works! Thank you :smile: :+1:
