### ISSUE TITLE
generic audio widgets

### ISSUE THREAD

**Issue by gajjanag** [copycat-killer/lain#104]
I happen to use PulseAudio as opposed to alsa for my audio needs. I noticed that your audio widget requires alsa-utils in order to access commands like amixer, etc. I wonder if it is possible to easily support PulseAudio as well, or more generally, if there is a method for obtaining/manipulating volume independent of alsa/PulseAudio, etc.

**Comment by copycat-killer** [comment]
Yes there is. See [base](https://github.com/copycat-killer/lain/wiki/base) or [abase](https://github.com/copycat-killer/lain/wiki/abase).

**Comment by gajjanag** [comment]
Thanks!
