### ISSUE TITLE
yawn is not available

### ISSUE THREAD

**Issue by Anniywell** [copycat-killer/lain#105]
I find my locationId, and request http://weather.yahooapis.com/forecastrss?u=c&w=2137082, it can work.
But when I use lain, it can't work, only have an icon

**Comment by copycat-killer** [comment]
This is a correct use.

```lua
-- Weather
yawn = lain.widgets.yawn(2137082,
{
    settings = function()
        widget:set_markup(" " .. forecast .. " " .. units .. "°C ")
    end
})
```
Be sure to add both icon and widget to a wibox, for instance the right one:

```lua
    right_layout:add(yawn.icon)
    right_layout:add(yawn.widget)
```
[Example screenshot](http://i.imgur.com/1GMW8HQ.png)

Read the [wiki](https://github.com/copycat-killer/lain/wiki/yawn) in order to do you customizations.

**Comment by Anniywell** [comment]
It's my rc.lua weather code
-- Weather
weathericon = wibox.widget.imagebox(beautiful.widget_weather)
yawn = lain.widgets.yawn(2137082, {
    settings = function()
        widget:set_markup(markup("#eca4c4", forecast:lower() .. " @ " .. units .. "°C "))
    end 
})

right_layout:add(weathericon)
right_layout:add(yawn.widget)

I think it's OK, but it also doesn't work!

**Comment by copycat-killer** [comment]
Indeed is OK, it's working here.

Trivial question: did you installed curl?

**Comment by Anniywell** [comment]
When I run 
curl --connect-timeout 1 -fsm 3 'http://weather.yahooapis.com/forecastrss?u=c&w=2137082'
in terminal
it can return results

**Comment by copycat-killer** [comment]
Paste me your `rc.lua`.

Also, try testing with [this version of yawn](https://gist.github.com/copycat-killer/05f4ccf662c4ab32f4f0).

Just replace `lain/yawn/init.lua` with this one, and tell me what it notifies you.

**Comment by Anniywell** [comment]
My rc.lua: http://pan.baidu.com/s/1dDB4hhB 
And I can't open https://gist.github.com/copycat-killer/05f4ccf662c4ab32f4f0

**Comment by copycat-killer** [comment]
Do the following:

+ execute these commands in a terminal

```shell
cd ~/.config/awesome/lain/widgets/yawn
mv init.lua init.lua.save
curl https://gist.githubusercontent.com/copycat-killer/05f4ccf662c4ab32f4f0/raw/23bf92706b3dc212e96bb27749453df238f9e226/init.lua >> init.lua 
```
- restart Awesome (press `Mod4 + Ctrl + r`)

* tell me the output in the upper right notifications

**Comment by copycat-killer** [comment]
I can't download from Baidu.

Please reupload your `rc.lua` to a saner host, like [Gist](https://gist.github.com/).

**Comment by Anniywell** [comment]
sorry, I can't access gist. Can you give me you email?

**Comment by copycat-killer** [comment]
You can't access Gist, but you have no problems with Github?!

My mail is in the repo readme.

Do the test above.

**Comment by Anniywell** [comment]
China...

**Comment by Anniywell** [comment]
I can't found your email in readme, please give me, thanks very much.
I have an another problem: fs format
![img_20150416_172511](https://cloud.githubusercontent.com/assets/5745585/7177980/c8067624-e45d-11e4-8ef1-c9701415a61c.jpg)

**Comment by copycat-killer** [comment]
dada [at] archlinux [dot] info (replace [at] with @ and [dot] with .)

**Do the test I told you above.**

For the calendar, [as you can the wiki](https://github.com/copycat-killer/lain/wiki/calendar#note), you have to use a monospaced font.

**Comment by copycat-killer** [comment]
How's going?

I just checked yawn again, and it's all working here.

Do you have latest Awesome and Lua versions?

PS: Install terminus-font from your distro repositories or [here](http://terminus-font.sourceforge.net).

**Comment by jeremymturner** [comment]
I had a possibly similar issue. I'm running awesome at work which requires an http proxy. curl on a regular command prompt honors the http_proxy/https_proxy environment variables, which work great. However, curl inside the lain lua file didn't seem to honor the environment variables.

I have a script that I run at work to set proxy information, I may try to hook my copy of lain in with that. Right now, I got it to work by hard-coding my proxy information into the curl command:

    local cmd = "curl -x http://hostname:port --connect-timeout 1 -fsm 3 '" .. url .. "'"

**Comment by Anniywell** [comment]
Sorry, I've been busy with other stuff recently.How can I do now?

**Comment by copycat-killer** [comment]
I'm thinking to switch to OpenWeatherMap, which is lighter and developer friendly.

What do you think?

**Comment by aajjbb** [comment]
I had issues with yawn, switching to OpenWeatherMap can be a good thing.

Also, @Anniywell how do you make such a pretty fs widget ? Do you load this by hand ? Could you show me the code ? Thanks

**Comment by copycat-killer** [comment]
@aajjbb It's [part of lain](https://github.com/copycat-killer/lain/blob/master/scripts/dfs).

**Comment by aajjbb** [comment]
@copycat-killer didn't know about it, thank you!

**Comment by gajjanag** [comment]
On the note of switching weather service to OpenWeatherMap, I notice that OpenWeatherMap exposes wind speed data, while the current widget does not provide wind speed due to the limitations of the yahoo webpage. While making the transition, could you please add it by default?

**Comment by ff2000** [comment]
It would be great if you could add an easy way to show multiple locations. E.g. by accepting an array of IDs instead of a single ID.

**Comment by copycat-killer** [comment]
@ff2000 It's not hard to implement, but I think it'd be better to keep this simple: want x locations? use x widgets. That x hardly would be > 5, plus every widget is light, asynchronous and indipendent.

**Comment by ff2000** [comment]
@copycat-killer yes, it is possible. I just like your default config, where Alt+W simply runs yawn.show() and everything is done ;)
And it won't be >5, yeah.
Will try to get yawn popup as notification with more than 1 station then.

**Comment by copycat-killer** [comment]
@ff2000 That is very simple to achieve, just build your own notification with text retrieved from the widgets set.

**Comment by Anniywell** [comment]
Sorry, i have already install desktop environment。So I can't reproduce this problem。If you need my rc，I can send to you。

**Comment by copycat-killer** [comment]
@Anniywell Don't worry, I'll keep this issue open until the new weather module is done.

**Comment by copycat-killer** [comment]
Finally I had some time to re-implement the module, this time based on the much more powerful OpenWeatherMap.

Less experienced users may find it a little bit more difficult to use it than Yawn, but it's the price you pay to have a fully customizable and extremely flexible module.

Read the [wiki](https://github.com/copycat-killer/lain/wiki/weather) for all the info.

Comment here for anything. In case of issues, I'll reopen the thread.

Closing for now.

**Comment by cr1ogen** [comment]
Hellow. Congrats for your works is amazing!! I have 2 errors in the file lain/widgets/wheater.lua
wheater.lua:72: bad argument 2 to'format' (string expected, got nil)
same in line 101.
Im a newbie in this, my question is, i have to midified this file or not.
Sorry for my english!! Regards from Argentina

**Comment by copycat-killer** [comment]
@cr1ogen You have to define `city_id`. Read the wiki.

**Comment by copycat-killer** [comment]
I added a failsafe check, altough this part should be obvious.
