### ISSUE TITLE
alsabar displays 0% all the time

### ISSUE THREAD

**Issue by aviau** [copycat-killer/lain#108]
```
local f = io.popen("amixer -M get " .. alsabar.channel)
```

was replaced by :

```
local f = assert(io.popen(string.format("amixer -c %s -M get %s", alsabar.card, alsabar.channel)))
```

And this is what broke it for me.

**Comment by copycat-killer** [comment]
There could be two reasons.

1. You didn't define `alsabar.card` properly. Here's an example:

  ```lua
  volume = lain.widgets.alsabar({width = 55, ticks = true, ticks_size = 6,
  card = "0", -- [...]
  ``` 
  Not `0`? Try `1`, or check `alsamixer`.

2. You did, but somehow it fails.

You tell me.

**Comment by aviau** [comment]
I don't really know how to interpret alsamixer's output.

![screenshot from 2015-05-19 08 44 51](https://cloud.githubusercontent.com/assets/2706882/7703225/7e6e02b4-fe04-11e4-83c9-d24e571e992f.png)

The right card is the default one. It has no number?

**Comment by copycat-killer** [comment]
There wasn't a previous behavior, all was left to `alsamixer`.

The card option has been introduced since there are some user with multiple cards.
