### ISSUE TITLE
uselesstile.lua:183: attempt to perform 'n%0'

### ISSUE THREAD

**Issue by sejoruiz** [copycat-killer/lain#109]
Hi!
First of all, thanks for this incredible package. I have been using using many layouts from it without problems, until Awesome was updated to 3.5.6 (yesterday). Then, every time I log in, I get an error saying:
`/usr/share/awesome/lib/lain/layout/uselesstile.lua:183 attempt to perform 'n%0'`
If you need my config files, just let me know, and I'll upload them into Github

**Comment by InsidiousMind** [comment]
I have this same exact problem too, just noticed it yesterday afternoon.

**Comment by pdk56** [comment]
I am also having this exact same issue, seems to only happen when there is one window open on a tag using the useless tile layout, the layout still works fine with more than one window open though.

**Comment by sejoruiz** [comment]
In my case, the moment the error is shown, the layouts are not working correctly anymore. If I open 2 windows at the same time, one will be displayed over the other one. At the moment, I've disabled all the lain layouts, and I'm working with the default ones.

**Comment by InsidiousMind** [comment]
If I have two windows open in a tag, then try tililng my layouts it will work. However the moment i close a window and try tiling again with only one window open I get the error and all my layouts get screwed up. If I disable all the lain.uselesstile layouts then everything works swell.

**Comment by copycat-killer** [comment]
Try 3a448b2.

**Comment by InsidiousMind** [comment]
Fixed the problem, thanks!
