### ISSUE TITLE
mpd always show N/A > N/A

### ISSUE THREAD

**Issue by Incognito4nonymous** [copycat-killer/lain#112]
Hello !

I have a little problem here, MPD is configured and is running, but when I launch music it always shows N/A > N/A.

And I don't know if the widget is supposed to work. directly of if it needs some extra set up.

I use the multicolor theme.

**Comment by copycat-killer** [comment]
Did you install `curl` and `telnet`?

Did you set the widget correctly? That is, correct MPD host address, MPD port and music directory?

If host is not the local one, are you sure of not being blocked by some firewall policy?

If yes is the answer to all, check if this command works:

```Shell
echo 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```
replace `MPD_HOST` and `MPD_PORT` correctly.

**Comment by Incognito4nonymous** [comment]
Curl and Telnet are installed, the path of my music is /home/incognito/Music

In the mpd.lua it is ("HOME") /Music

I made a mistake ? Excuse me for my bad English I'm french.

**Comment by aajjbb** [comment]
Dou you pass your music directory as the argument 'music_dir' when you create the widget ?

**Comment by copycat-killer** [comment]
@Incognito4nonymous give me the output of this command:


```Shell
echo 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```
replace `MPD_HOST` and `MPD_PORT` correctly (default are 127.0.0.1 and 6600, if you didn't touch anything).

**Comment by Incognito4nonymous** [comment]
Erm... Well that's embarrassing, I've broken my laptop today and Awesome was on it.

I don't have it with me and I'm currently typing on my phone.

It will be repaired in a month.

Sorry.

-Incognito.

**Comment by copycat-killer** [comment]
I'd like to know if this is a real issue or a bad configuration of yours.

Please, test it again on another pc if you have any chance.

**Comment by copycat-killer** [comment]
Feel free to comment whenever you'll need it in the future.

Closing for now.

**Comment by Incognito4nonymous** [comment]
Hello again !

I'm now using a USB keyboard. So :

the layout is OK MPD 0.19.0
ACK [5@0] {} Invalid word character

**Comment by copycat-killer** [comment]
Is that an error or what the widget displays?

**Comment by Incognito4nonymous** [comment]
it is the layout of this command
echo 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT

**Comment by copycat-killer** [comment]
I added a `-e` to the echo command:

```lua
echo -e 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```

Pull latest commt and tell me if it's ok now.

**Comment by Incognito4nonymous** [comment]
Here is the layout 

OK MPD 0.19.0
volume: -1
repeat: 1
random: 0
single: 1
consume: 0
playlist: 2
playlistlength: 319
mixrampdb: 0.000000
state: stop
song: 49
songid: 50
nextsong: 49
nextsongid: 50
OK
file: My sounds/Music loop/mr/feelin.mp3
Last-Modified: 2014-10-26T22:51:08Z
Time: 118
Pos: 49
Id: 50
OK

**Comment by copycat-killer** [comment]
Try the widget with latest lain.

**Comment by ff2000** [comment]
I have the same issue.
If I replace "echo -e <...>" by "echo <...>" in mpd.lua:43 I get the correct status back. Don't know how the "-e" arg can cause issues here :/
```
$ readlink /bin/sh
/bin/dash
                                                                                                                                                                                                       
~
$ echo $SHELL
/bin/zsh
```

**Comment by copycat-killer** [comment]
I don't know that either. I'll investigate further.

**Comment by ff2000** [comment]
It seems to be dash vs bash. Symlinking bash to /bin/sh makes the widget work again.
@Incognito4nonymous do you have /bin/sh point to something else than bash?

**Comment by Incognito4nonymous** [comment]
I don't know, what am I supposed to do know it ?

**Comment by ff2000** [comment]
Try `readlink $(which sh)`

**Comment by copycat-killer** [comment]
Maybe we can set `/bin/bash` as an environment variable.

@Incognito4nonymous try the following command:

```lua
SHELL=/bin/bash echo 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```

or

```lua
env SHELL=/bin/bash echo 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```

**Comment by Incognito4nonymous** [comment]
Just for being sure, I have to use that command in the mpd.lua file right ?

**Comment by Unode** [comment]
How about using `/bin/echo` instead of relying on the shell?

**Comment by copycat-killer** [comment]
Ok, try to use `/bin/echo -e`, everyone.

**Comment by copycat-killer** [comment]
^ Added for testing in e5e199c.

**Comment by ff2000** [comment]
Luke Bonham wrote:
> ^ Added for testing in e5e199c.
Seems to work here, even with dash.

**Comment by Incognito4nonymous** [comment]
/bin/echo -e still doesn't work...

**Comment by copycat-killer** [comment]
@Incognito4nonymous 

`/bin/echo -e` doesn't work, but `echo -e` does.

What kind of echo do you have??

Out of curiosity, try this:

```shell
/usr/bin/echo -e 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://MPD_HOST:MPD_PORT
```

**Comment by Incognito4nonymous** [comment]
bash-4.2$ /usr/bin/echo -e 'status\ncurrentsong\nclose' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600
OK MPD 0.19.0
volume: 100
repeat: 1
random: 0
single: 1
consume: 0
playlist: 2
playlistlength: 319
mixrampdb: 0.000000
state: play
song: 43
songid: 44
time: 4:186
elapsed: 3.657
bitrate: 128
audio: 44100:24:2
nextsong: 43
nextsongid: 44
OK
file: My sounds/Music loop/MS-29 Star Wars The Imperial March.mp3
Last-Modified: 2014-09-05T08:35:54Z
Time: 186
Pos: 43
Id: 44
OK

**Comment by Unode** [comment]
```
% /usr/bin/env echo --help

Usage: echo [SHORT-OPTION]... [STRING]...
  or:  echo LONG-OPTION
Echo the STRING(s) to standard output.

  -n             do not output the trailing newline
  -e             enable interpretation of backslash escapes
  -E             disable interpretation of backslash escapes (default)
      --help     display this help and exit
      --version  output version information and exit

If -e is in effect, the following sequences are recognized:

  \\      backslash
  \a      alert (BEL)
  \b      backspace
  \c      produce no further output
  \e      escape
  \f      form feed
  \n      new line
  \r      carriage return
  \t      horizontal tab
  \v      vertical tab
  \0NNN   byte with octal value NNN (1 to 3 digits)
  \xHH    byte with hexadecimal value HH (1 to 2 digits)

NOTE: your shell may have its own version of echo, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.

Report echo bugs to bug-coreutils@gnu.org
GNU coreutils home page: <http://www.gnu.org/software/coreutils/>
General help using GNU software: <http://www.gnu.org/gethelp/>
For complete documentation, run: info coreutils 'echo invocation'

```

**Comment by copycat-killer** [comment]
It seems the only option left is this.

An `echo_cmd` argument, default to "echo".

@Incognito4nonymous update to latest lain and set your MPD widget like this:

```lua
mpdwidget = lain.widgets.mpd({
    echo_cmd = "echo -e",
    settings = function()
        -- [...]
    end
})
```

**Comment by Incognito4nonymous** [comment]
N/A.

**Comment by copycat-killer** [comment]
Try one of the options above.

I don't want to believe that this is not working.

**Comment by Unode** [comment]
@Incognito4nonymous for something as simple as `echo` to cause so much trouble... What distribution are you using? Linux, BSD?

**Comment by Incognito4nonymous** [comment]
I'm using Slackware.

**Comment by copycat-killer** [comment]
@Incognito4nonymous Did you configure the widget like above? Did you try some other `echo_cmd`? Come on.

**Comment by Incognito4nonymous** [comment]
Could this be a permission problem ?

**Comment by copycat-killer** [comment]
Surely not for us. Can't you verify it on your machine?

**Comment by Incognito4nonymous** [comment]
Ok, definitely not a perm prob.

I'm now wondering if i didn't missed something.

**Comment by copycat-killer** [comment]
Instead of wondering, please provide your widget configuration.

Also, double check MPD configuration, and [be sure to have it active when using the widget](https://github.com/copycat-killer/lain/issues/23#issuecomment-41815756).

**Comment by Incognito4nonymous** [comment]
I configured MPD myself, and mpc, ncmpc and ncmpcpp are working flawlessly.

For the widget, I am using an out of the box one. (with the /bin/echo -e)

**Comment by copycat-killer** [comment]
If it's not a permission problem (really sure?) then try various `echo_cmd`.

I don't know, `/usr/bin echo -e`,  `/bin echo -e`, whatever else.

I runned out of ideas for you.

**Comment by copycat-killer** [comment]
@Incognito4nonymous updates?

Sorry for the double notification, but I want to solve this.

**Comment by Incognito4nonymous** [comment]
I use XMMS now, so I stopped to use MPD or ncmpcpp, sorry.

**Comment by copycat-killer** [comment]
Ok, I assume this can only be related to your very specific (or shall I say unique) configuration.

If you want to come back to this, you can reply and I'll reopen the thread.

Closing again.

**Comment by Incognito4nonymous** [comment]
Hello ! As Schwarzenegger would say : 
"I'm Back !"
I have since updated to a new release of Slackware, the 14.2 and therefore, I have re-done all the configurations.
I finally got the widget to work (gave me some salt however)
And since I have downloaded some albums since, the new songs appeared perfectly, while the old ones always displayed that f****ing NA > NA.
But why ?
The songs aren't tagged, so tonight I'll download EasyTag, and I'll give it a try, I'm sure this is the issue.
I also forgot to add, the widget shows the song name, but not the album cover.

**Comment by copycat-killer** [comment]
Did you set the infos in your files? Does this still happen?

**Comment by Incognito4nonymous** [comment]
It happens to untagged files only ;)
Yet I have spent hours tagging them, it works like a dream now, except for the Cover art that doesn't display.

**Comment by copycat-killer** [comment]
Everything ok then, because if the file doesn't have any info, MPD can't show any info.
