### ISSUE TITLE
Prevent mpd cover search when streaming

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#115]
The command issued at https://github.com/copycat-killer/lain/blob/master/widgets/mpd.lua#L92 causes a lot of ```find: `/home/u/Music/http://': No such file or directory``` errors in the logs.
It basically breaks when mpd is used with http streams.

It's also not entirely clear if the call to `os.execute` could lead to a command injection by providing a malformed URL.

**Comment by copycat-killer** [comment]
Never used it with streams, so this is a good time to enhance it. Thanks.

> It's also not entirely clear if the call to os.execute could lead to a command injection by providing a malformed URL.

It could lead to an injection by providing any malicious argument. But you are the only one feeding it, where's the point in that?

Instead, with an HTTP url the command will fail to use [mpdcover](https://github.com/copycat-killer/lain/blob/master/scripts/mpdcover), so there's no harm.

**Comment by copycat-killer** [comment]
Since you did not update me on this, I tested myself and it's working here.

If for some reason you'll still have issues, comment back.

**Comment by Unode** [comment]
Hi. Sorry I didn't get notified after your commit (or it passed unnoticed).

It works. The exception may be `https://` but I haven't used any such stream so far.

Thanks
