### ISSUE TITLE
fs.lua:109: in attempt to index a nil value (global 'widget')

### ISSUE THREAD

**Issue by Jeremmm** [copycat-killer/lain#116]
Hello,

We have an issue with a fresh install (archlinux).
When I want apply multicolor theme, I have two errors :

first error
/home/jeremmm/.config/awesome/lain/widgets/fs.lua:109: attempt to index a nil value (global 'widget')

second error
error while running function
stack traceback:
  /home/jeremmm/.config/awesome/lain/widgets/fs.lua:109: in function </home/jeremmm/.config/awesome/lain/widgets/fs.lua:56>
  (...tail calls...)
  /home/jeremmm/.config/awesome/rc.lua:149: in main chunk
  error: /home/jeremmm/.config/awesome/lain/widgets/fs.lua:109: attempt to index a nil value (global 'widget')

copycat and lain files are latest version.

lua 5.3.1
awesome v3.5.6

If you have an idea for there error, I'm interested.

Thanks

**Comment by aajjbb** [comment]
It was a small typo in the last commit. Already issued a pull request to fix it.

**Comment by Jeremmm** [comment]
can you tell me where is the typo until either correct the git?

**Comment by Jeremmm** [comment]
It's good I have seen thy push request. thank you :)
