### ISSUE TITLE
mpdwidget is flooding logs

### ISSUE THREAD

**Issue by spectromas** [copycat-killer/lain#119]
I am using the configuration for mpdwidget from awesome-copycats configs. When this is enabled my system logs are getting flooded with mpd messages: 

    Jul 14 13:48:26 localhost mpd[1764]: client: [137] closed
    Jul 14 13:48:28 localhost mpd[1764]: client: [138] opened from 127.0.0.1:34494
    Jul 14 13:48:28 localhost mpd[1764]: client: [138] closed
    Jul 14 13:48:30 localhost mpd[1764]: client: [139] opened from 127.0.0.1:34495
    Jul 14 13:48:30 localhost mpd[1764]: client: [139] closed
    Jul 14 13:48:32 localhost mpd[1764]: client: [140] opened from 127.0.0.1:34496
    Jul 14 13:48:32 localhost mpd[1764]: client: [140] closed
    Jul 14 13:48:34 localhost mpd[1764]: client: [141] opened from 127.0.0.1:34497
    Jul 14 13:48:34 localhost mpd[1764]: client: [141] closed
    Jul 14 13:48:36 localhost mpd[1764]: client: [142] opened from 127.0.0.1:34498
    Jul 14 13:48:36 localhost mpd[1764]: client: [142] closed
    Jul 14 13:48:38 localhost mpd[1764]: client: [143] opened from 127.0.0.1:34499
    Jul 14 13:48:38 localhost mpd[1764]: client: [143] closed
    Jul 14 13:48:40 localhost mpd[1764]: client: [144] opened from 127.0.0.1:34500
    Jul 14 13:48:40 localhost mpd[1764]: client: [144] closed
    Jul 14 13:48:42 localhost mpd[1764]: client: [145] opened from 127.0.0.1:34501
    Jul 14 13:48:42 localhost mpd[1764]: client: [145] closed
    Jul 14 13:48:44 localhost mpd[1764]: client: [146] opened from 127.0.0.1:34503
    Jul 14 13:48:44 localhost mpd[1764]: client: [146] closed
    Jul 14 13:48:46 localhost mpd[1764]: client: [147] opened from 127.0.0.1:34504
    Jul 14 13:48:46 localhost mpd[1764]: client: [147] closed
    Jul 14 13:48:48 localhost mpd[1764]: client: [148] opened from 127.0.0.1:34505
    Jul 14 13:48:48 localhost mpd[1764]: client: [148] closed
    Jul 14 13:48:50 localhost mpd[1764]: client: [149] opened from 127.0.0.1:34508
    Jul 14 13:48:50 localhost mpd[1764]: client: [149] closed
    Jul 14 13:48:52 localhost mpd[1764]: client: [150] opened from 127.0.0.1:34509
    Jul 14 13:48:52 localhost mpd[1764]: client: [150] closed

I don't know if this is a bug or something wrong on my end but I would like to get to the bottom of if possible, I really like using this widget. 
My mpd.conf has logging disabled.

**Comment by copycat-killer** [comment]
Nothing wrong, it's just the widget polling.

It uses a network protocol because of MPD server architecture, that's why all those logs.

**Comment by spectromas** [comment]
Ok thanks, if there is no way to prevent this then I'll just have to sed my logs or something then.
