### ISSUE TITLE
Weather widget not working

### ISSUE THREAD

**Issue by paescuj** [copycat-killer/lain#121]
I use the awesome-copycats theme "holo"  and keep getting the following error with the weather widget:

```
weather.lua:82: bad argument #1 to 'read' (invalid option)
```

The local repository is on the latest version and I've adjusted the "city_id".

Unfortunately, I'm not very familiar with Lua...

**Comment by 13337** [comment]
changing line 82 of $AWESOME_CONFIG_DIR/lain/widgets/weather.lua from

>                     day = string.gsub(f:read("a"), "\n", "")
 to
                    day = string.gsub(f:read("*a"), "\n", "")
 
fixed this issue for me. Was experiencing it with rc.lua.multicolor. Don't know why it works, but it appears to.

**Comment by copycat-killer** [comment]
@paescuj Try the suggested fix, or pull 4d5d37f.

**Comment by copycat-killer** [comment]
Replaced `*a` to `*all` in every `io.read` to respect the standard syntax.

**Comment by copycat-killer** [comment]
This should be fixed, but reply in case of need. Closing.
