### ISSUE TITLE
Centerfair: how to invert master window position

### ISSUE THREAD

**Issue by tigrisathon** [copycat-killer/lain#123]
Hello! As I can see, in centerfair layout master window is always in the end. For example, if i open 4 windows (I have 2 columns on my screen), that's how they will be placed: 4th window will be in the left half of the screen, and 3rd, 2nd, 1st windows will share the right half of the screen, and 1st window (master) will be in the bottom. In this situation I would like to have 1st (master) window in the left half of the screen, and all other windows - sharing the right half (newest window - in the bottom) (e.g, older windows have higher priority). Could you please tell me, how to implement that basing on centerfair (that feature of having window centered if there is only one window is very useful for me)? Thank you.

**Comment by copycat-killer** [comment]
Basically you're asking for an "inverse" centerfair.

Which would be like `lain.layout.uselesstile`, but centered instead of maximized when there's one window only.

So I suggest to fork this last one, and to do your changes `tile_column`, [here](https://github.com/copycat-killer/lain/blob/master/layout/uselesstile.lua#L96).

It shouldn't take much, I'll give a look myself later.

**Comment by tigrisathon** [comment]
Yes. Actually, what I am dreaming of, is total analogue of "awful.layout.suit.tile", but with centered window, if there is only one window. Unfortunately, I am a beginner in configuring awesome. However, I will try to do something :-) Probably, I will even succeed.

**Comment by tigrisathon** [comment]
I tried to do something, but did not succeed. If you decided to implement such layout, i would be very happy

**Comment by worron** [comment]
@tigrisathon, try to add this code to [line 139](https://github.com/copycat-killer/lain/blob/master/layout/uselesstile.lua#L139) in `lain.layout.uselesstile`
```lua
if #cls == 1 then
	local sg = beautiful.single_gap or { width = 0, height = 0 }
	local sg = { width = 500, height = 200 } -- this line for testing only, should be removed later
	local correction = { x = sg.width / 2, y = sg.height / 2, width = - sg.width, height = - sg.height }
	for k, v in pairs(correction) do wa[k] = wa[k] + v end
 end
```

**Comment by tigrisathon** [comment]
It works and it's wonderful! Thank you!
Just a little question: after removing the line marked for testing, this layout behaves just as standard tile layout - if one window, it goes fullscreen. What should i do to this line?

**Comment by worron** [comment]
After removing this line you will be able config single window size from your theme file. In `theme.lua` add something like
```
theme.single_gap = { width = 600, height = 100 }
```

**Comment by tigrisathon** [comment]
Thank you, everything fine!

**Comment by copycat-killer** [comment]
@worron Thanks for your time.

[I've updated the wiki.](https://github.com/copycat-killer/lain/wiki/Layouts#centerfair)
