### ISSUE TITLE
helpers.lua doesn't work with awesome build from git, "master" branch

### ISSUE THREAD

**Issue by tigrisathon** [copycat-killer/lain#124]
awesome v3.5.2-539-g2c3c6b5 (The Fox)
 • Build: Jul 19 2015 10:46:31 for x86_64 by gcc version 4.9.2 (root@debian)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

When I tried to use some of lain widgets, I got error:
https://i.imgur.com/sYAaGl2.png

I looked at helpers.lua, and could make it work, after changing "Timer marker" section this way:

timer_table = {}
function helpers.newtimer(name, timeout, fun, nostart)
    timer_table[name] = timer({ timeout = timeout })
    timer_table[name]:connect_signal("timeout", fun)
    timer_table[name]:start()
    if not nostart then
        timer_table[name]:emit_signal("timeout")
    end
end

However, I do not think this is a nice solution.

**Comment by copycat-killer** [comment]
As the error says, it seems that your building system doesn't have the C API timer section.

Your "solution" is using a table which seems to be local-scope defined, not the real API one.

Why you need to use the unstable branch? And why an old one? 

If you want the git version, it's mandatory to use the latest awesome and Lua.

**Comment by tigrisathon** [comment]
I use unstable branch, as a few patches important for me were added to it recently. Probably, I should have just patched the stable version...
Is "master" an old one? I thought, "master" is the newest version.
As it is not a bug in lain, sorry for disturbing you.

**Comment by copycat-killer** [comment]
Your "master" awesome 3.5.2 compiled against Lua 5.1.5.

While latest stable is awesome 3.5.6 compiled against Lua 5.3.0.

That's why I said it's an old one.

So, I suggest you to try the latest stable (since it is +0.0.4 versions ahead yours, maybe the patch you need has been merged, check its changelog).

Otherwise, be sure to grab the real newest version.

**Comment by tigrisathon** [comment]
Could you please advise me, where can I get true latest git version of awesome? As I can see, all the commits go to "master". Doesn't it mean, that Master is the latest?

**Comment by copycat-killer** [comment]
"Master" refers to the git branch. Usually it's the "up to date" version, but in some cases there may be some testing branches way ahead (like it seems for current Debian packages).

[Here](http://awesome.naquadah.org/download) you can find your info. Try 3.5.6 first.

Feel free to ask me further questions. When you're done, please close this issue thread.

**Comment by tigrisathon** [comment]
As i can see from https://github.com/awesomeWM/awesome/branches, currently "master" is really the newest.
Anyway, I am going to try to apply commits, which are important for me, to 3.5 locally. Thank you for your readiness to help!

**Comment by tigrisathon** [comment]
Excuse me, one more question appeared.
As you say, this problem appeared because doesn't have the C API timer section.
What actually caused it? Wrong Awesome version, wrong Lua version or it's some C headers' fault. Generally, what should be done to fix it in a correct way?

**Comment by copycat-killer** [comment]
I think that's related to awesome version, and the Lua version used to build it.

The correct "fix" is always the same: be sure to have latest stable versions.

You can use the latest awesome git version if you prefer, but be sure to have latest Lua (currently is 5.3.1).

**Comment by tigrisathon** [comment]
Thank you. Currently I faced some problems while backporting changes important for me to 3.5.6, but I think, I will be able to resolve them soon.

**Comment by tigrisathon** [comment]
Thank you. Currently I faced some problems while backporting changes important for me to 3.5.6, but I think, I will be able to resolve them soon.
