### ISSUE TITLE
Widget positioning with multiple monitors

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#125]
Hi there,

When using a multi monitor/screen setup (say 2), if the widget in the second screen is hovered, the "popup" shows up on the first.
Seen with, for instance, `widgets.fs` and `widgets.calendar`.

Is there any way to customize this?

**Comment by copycat-killer** [comment]
Yes, you can customize screen number popup for every supported widget.

For `fs`, set `fs_notification_preset.screen = yournumber` within the `settings` function.

For, `calendar`, set `scr_pos` as input argument.

Read the wiki for the rest.

**Comment by Unode** [comment]
Thanks for the references.

Would it be possible to have these arguments dynamically set (or modified) based on the mouse or the widget location (screen)?

Wondering how to get the popups on the same screen as the widget without having to create new/custom sets of widgets for every screen.

Thanks.

**Comment by copycat-killer** [comment]
It should be possible like this:

```lua
local mouse = mouse

-- [...]

notification_preset.screen = mouse.screen
```

**Comment by Unode** [comment]
Yup that works.

Pull request linked.
