### ISSUE TITLE
Feature request: mouse_resize_handler like in awful.layout.suit.tile

### ISSUE THREAD

**Issue by jaysonwillson** [copycat-killer/lain#127]
Hello! Standard awful layouts have a nice feature: if you do Meta+Right Click and move cursor to left/right, border between the windows will move to left/right (awful.tag.incmwfact). If you implemented it in your layouts (especially good for uselessfair, uselesstile) - it would be great.

**Comment by copycat-killer** [comment]
#48 #87 

I am just waiting for the next stable awesome version which will support it.

**Comment by jaysonwillson** [comment]
Understood, thank you. Will be waiting for next stable awesome release impatiently

**Comment by copycat-killer** [comment]
If mouse resizing is vital for you, you can pass to awesome unstable branch and merge fix #87 by yourself.
