### ISSUE TITLE
net widget net_now.send returning nil causing error popup in awesome

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#129]
Hi,

The net_now.received is working but the net_now.send is always returning nil.

**Comment by copycat-killer** [comment]
Because it's sen**t**, not sen*d*.

If yours was just a typo, please provide me an example in order to reproduce the problem.

**Comment by dummys** [comment]
omg you are right. Damn typo... I feel like dumb, sorry for disturbing.
