### ISSUE TITLE
bg color with alpha messes up naughty.notify (calendar widget)

### ISSUE THREAD

**Issue by everslick** [copycat-killer/lain#131]
in calendar widget:

i had set the bg color with an alpha channel, but the bg color becomes the fg color for TODAY, thus making the renderer show the html instead of some fallback. took me an whole evening to track that sucker down. :-/

i suggest the following fix:

[  ]    calendar.font_size   = tonumber(args.font_size) or 11
[  ]    calendar.fg          = args.fg or beautiful.fg_normal or "#FFFFFF"
[?]    calendar.bg          = args.bg or beautiful.bg_normal or "#000000"
[  ]    calendar.position    = args.position or "top_right"
[  ]    calendar.scr_pos     = args.scr_pos or 1
[  ]    calendar.followmouse = args.followmouse or false

[+]    calendar.fg          = string.sub(calendar.fg, 1, 7)
[+]    calendar.bg          = string.sub(calendar.bg, 1, 7)

[  ]    calendar.offset      = 0

change the line with the '?' (copy paste error?) and add the lines with '*'

btw: why all this mess with sed and pipes and not using string.gsub() instead? are you interested in a patch for that?

best regards!

**Comment by copycat-killer** [comment]
Feel free to pull request a patch for both things.

**Comment by copycat-killer** [comment]
satisfied by #132
