### ISSUE TITLE
calendar.lua badly retreives beautiful font when spaces are present

### ISSUE THREAD

**Issue by d125q** [copycat-killer/lain#139]
```lua
calendar.font = args.font or beautiful.font:sub(beautiful.font:find(""), beautiful.font:find(" "))
```
does not really work well. Consider the case when `beautiful.font = "Source Code Pro 11"` -- `calendar.font` ends up being `"Source"`, which is definitely not intended.

Proposed solutions:
```lua
calendar.font = args.font or beautiful.font:gsub(" %d+$", "")
-- OR --
calendar.font = args.font or "monospace"
```
The first option simply fixes the currently present code (i.e. even if `beautiful.font = "Source Code Pro 11"`, `calendar.font` still results in `"Source Code Pro"`). The second option, however, is due to the fact that we really need a monospaced font, and maybe `beautiful.font` isn't monospaced and will cause the calendar by default to look bad. Which one do you prefer?

**Comment by copycat-killer** [comment]
The first one won't work if I have something like "Tamsyn 10.5", while the second one requires monospace to be installed.

The `beautiful.font` retrieval is a shortcut if the user is already using a system wide monospaced font. Otherwise `args.font` can be specified. This is how it was intended to be.

Cutting from the first number to the EOF should do it.

Try out 5e8b639.

**Comment by d125q** [comment]
You are correct that it won't work in that case.

As for the other issue, the `"monospace"` font is always present (so are `"serif"` and `"sans-serif"`).

**Comment by copycat-killer** [comment]
> As for the other issue, the "monospace" font is always present

It might be odd, but I don't have it installed.

Does the latest commit solve this?

**Comment by d125q** [comment]
Yes -- it works well (i.e. it correctly picks the font set by `beautiful` even if it contains spaces).

`"monospace"`, `"sans-serif"`, and `"serif"` are simply 'default' names used by fontconfig and are replaced by other fonts. That's why they're 'always' available. Try `fc-match monospace` and you will see what font `"monospace"` gets replaced by on your machine. I brought this up because `beautiful.font` *may not be* monospaced, causing the calendar to look weird.

**Comment by copycat-killer** [comment]
> I brought this up because beautiful.font may not be monospaced, causing the calendar to look weird.

Understood, but that's why calendar font is an argument.
