### ISSUE TITLE
calendar: Attempt to concatenate a nil value

### ISSUE THREAD

**Issue by alferpal** [copycat-killer/lain#140]
After a system update on my machine ( Arch 64 bits, lain updated to the last commit ) whenever my mouse gets close to the calendar widget I get a bunch of the following errors thrown in a row:

/home/akai/.config/awesome/lain/widgets/calendar.lua:90: attempt to concatenate a nil value.

Awesome version:

awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔

I think this has started since I've updated this morning, after ncurses 6.0 rebuild on the testing repos.
 
Current version on my machine of the deps listed on the wiki are:
alsa-utils 1.0.29-2
curl 7.44.0-1
imagemagick 6.9.2.0-1

Should I check for another package version? Or how can I be of more help?

**Comment by copycat-killer** [comment]
Check if `font` and `font_size` are correctly set (or fetched from `beautiful`, in the first case).

Check also if `cal` or `/usr/bin/cal` is alright for you.

**Comment by alferpal** [comment]
The problem turned to be cal, being broken after the mentioned update, missing rebuild of (lib)util-linux. After rebuilding it for the soname bump on ncurses, everything is working again.

Sorry for reporting a problem that turnet not to be yours and thanks for the help.

**Comment by copycat-killer** [comment]
Don't worry, I'm here to help.

Feel free to ask anything.
