### ISSUE TITLE
mpd widget doesn't work when fish is set as the default login shell.

### ISSUE THREAD

**Issue by TheReverend403** [copycat-killer/lain#145]
No errors, just no output from the mpd widget, and no notifications. All other widgets that use the shell work fine.

**Comment by copycat-killer** [comment]
Tell me the exact steps to reproduce this.

**Comment by TheReverend403** [comment]
* Install http://fishshell.com/

* Set it as your default shell with ```chsh -s /bin/fish```, then relogin. Alternatively, use [xephyr](http://awesome.naquadah.org/wiki/Using_Xephyr) with the environment variable SHELL set to /bin/fish, it seems to work just as well. You should probably do this as a preferred method, because depending on how you launch X, your startup scripts like xinit may also be incompatible with fish without some tweaks.

* Observe how the MPD widget doesn't do anything.

As a sidenote, certain other things are not fish compatible, such as run_once(). [I already have a workaround](https://github.com/TheReverend403/awesome-config/blob/master/rc.lua#L51-L85) for that, and if you need it, I can make a PR for it.

**Comment by TheReverend403** [comment]
Also of interest is that I can run the exact curl command used in mpd.lua manually, and it produces expected output. I suspect the issue may be in asyncshell, but I haven't been able to produce any results from modifying it.

**Comment by TheReverend403** [comment]
Here we go, I figured out how to get Awesome's stdout.
````
Thunar: D-BUS name org.xfce.Thunar already registered.
Flag 0x0001, status 0, EXIT 1 STAT 0
fish: Could not expand string “"asyncshell.deliver(1, [[\"$(echo 'password 
status
currentsong
close' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600)\"]])"”
Standard input: echo "asyncshell.deliver(1, [[\"$(echo 'password 
                     ^

fish: Could not expand string “"asyncshell.deliver(2, [[\"$(echo 'password 
status
currentsong
close' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600)\"]])"”
Standard input: echo "asyncshell.deliver(2, [[\"$(echo 'password 
                     ^
fish: Could not expand string “"asyncshell.deliver(3, [[\"$(echo 'password 
status
currentsong
close' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600)\"]])"”
Standard input: echo "asyncshell.deliver(3, [[\"$(echo 'password 
                     ^
fish: Could not expand string “"asyncshell.deliver(4, [[\"$(echo 'password 
status
currentsong
close' | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600)\"]])"”
Standard input: echo "asyncshell.deliver(4, [[\"$(echo 'password
````

**Comment by TheReverend403** [comment]
OK, adding ````awful.util.shell = '/bin/sh'```` after line 15 of asyncshell.lua fixes it. Is this an acceptable workaround for compatibility across multiple shells?

**Comment by copycat-killer** [comment]
Yes.

**Comment by Unode** [comment]
Keep in mind that `/bin/sh` may still be a different shell (usually `bash` or `dash`) depending on the system.

[Some incompatibilities](http://mywiki.wooledge.org/Bashism) may still show up in some cases.

**Comment by copycat-killer** [comment]
Then, for those special cases, I'll wrote a line in the widgets section.
