### ISSUE TITLE
Two network widgets (for two different ifaces) problem

### ISSUE THREAD

**Issue by sudo-nice** [copycat-killer/lain#150]
I've added two instances of the network widget:
```lua
net0 = lain.widgets.net({
		iface = "eth0",
		settings = function()
		widget:set_text(net_now.received .. " " .. net_now.sent)
		end
		})

net1 = lain.widgets.net({
		iface = "eth1",
		settings = function()
		widget:set_text(net_now.received .. " " .. net_now.sent)
		end
		})
```
but looks like they are stalled. If I remove any of them, the other starts working. Can it be fixed?

**Comment by copycat-killer** [comment]
#61

**Comment by sudo-nice** [comment]
Thank you for the hint, but have you noticed, I mentioned two widgets to monitor two separate network interfaces: eth0 and eth1? I just can't get, how https://github.com/copycat-killer/lain/issues/61 can help me.

**Comment by deploychefapp** [comment]
Luke for some reason I get emails from your branch. Any Idea I can set this off?

Thanks ed
--
Kind regards,

Eddi Alim

Chef.One
+49-176-30333680 | eddi@chef.one <mailto:eddi@chef.one>
 
1% against hunger!

**Comment by copycat-killer** [comment]
@sudo-nice

No, I didn't.

How it's possible to have two different `iface` working at the same time, and why?

@deploychefapp 

I guess you have to "unwatch" this branch, or check your notification settings here.

**Comment by sudo-nice** [comment]
One device provides me an Internet connection, and the other is for my LAN communication.

**Comment by copycat-killer** [comment]
@sudo-nice check d659c34

**Comment by sudo-nice** [comment]
The widgets are not stalled anymore, but both display the same values.

**Comment by copycat-killer** [comment]
Try putting "local" before `iface` [at line 45 in `lain/widgets/net.lua`](https://github.com/copycat-killer/lain/blob/master/widgets/net.lua#L45).

**Comment by sudo-nice** [comment]
It works! You're great!

**Comment by copycat-killer** [comment]
I never thought about this kind of usage, in the end this an enhancement, so thanks.
