### ISSUE TITLE
bat widget returns "N/A" value all the time

### ISSUE THREAD

**Issue by ak114** [copycat-killer/lain#151]
`bat_now.perc` is returning "N/A", whether I plug my laptop or not.

Just having this:
```lua
batwidget = lain.widgets.bat({
    settings = function()
        perc = bat_now.perc .. "% "
        widget:set_text(perc)
    end
)}
```
My laptop (could help I guess): MSI GS70 2PC-419X.

**Comment by copycat-killer** [comment]
Set `battery` to "BAT1" or whatever `ls /sys/class/power_supply/` returns. Example:

```lua
batwidget = lain.widgets.bat({
    battery  = "BAT1", 
    settings = function()
        perc = bat_now.perc .. "% "
        widget:set_text(perc)
    end
)}
```

I'm almost sure this is it, but I'll wait for a confirmation.

**Comment by copycat-killer** [comment]
Also, it's good practice [to read the wiki](https://github.com/copycat-killer/lain/wiki/bat#note).

**Comment by ak114** [comment]
My bad. I went checking but I didn't look the notes, I'll be testing right now.

**Comment by copycat-killer** [comment]
Dont' worry, glad it's ok now. :dancers:
