### ISSUE TITLE
mpd external keybiding

### ISSUE THREAD

**Issue by aajjbb** [copycat-killer/lain#154]
Hi,

I've just decided to move from *cmus* to *mpd + ncmpcpp* and realized that external keybinding as shown in wiki no longer works, have you guys found another way to control ncmpcpp externally with lain ?

ncmpcpp version: 0.7
mpd version: 0.19.12

Thanks.

**Comment by copycat-killer** [comment]
Install `mpc` as well and let it do it the usual shell command. From a rapid check, `ncmpcpp` seems to have changed its usability.

**Comment by aajjbb** [comment]
Great, that works. Thank you.
