### ISSUE TITLE
Bat widget returning wrong percentage

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#155]
Hello, 
on my macbookpro I got wrong percentage with the widget:

Example with widget:
Bat 74

Example wih ACPI:
Battery 0: Discharging, 89%, 03:00:29 remaining

It's more accurate to use `acpi` with `cut` like this:

([source](http://awesome.naquadah.org/wiki/Gizmoguy's_super-easy_acpi_battery_widget))

```lua
batterywidget = wibox.widget.textbox()    
batterywidget:set_text(" | Battery | ")    
batterywidgettimer = timer({ timeout = 5 })    
batterywidgettimer:connect_signal("timeout",    
  function()    
    fh = assert(io.popen("acpi | cut -d, -f 2,3 -", "r"))    
    batterywidget:set_text(" |" .. fh:read("*l") .. " | ")    
    fh:close()    
  end    
)    
batterywidgettimer:start()
```

What do you think?

**Comment by copycat-killer** [comment]
This project targets GNU/Linux derivatives, I don't have a Mac neither I know how battery management works on OSX.

You can help me trying to enhance the battery widget, or you can just use [`base`](https://github.com/copycat-killer/lain/wiki/base) like this:

```lua
batterywidget = lain.widgets.base({
    cmd = "acpi | cut -d, -f 2,3 -",
    settings = function()
        widget:set_text(" | " .. output .. " | ") 
    end
})
```

**Comment by dummys** [comment]
I use awesome on linux on my macbookpro, not osx...

Ok I will create one and post it here.

**Comment by dummys** [comment]
Something like this:

batwidgetnew = lain.widgets.base({
    cmd = "acpi | cut -d, -f 2,3| awk '{gsub(/%/,\"\"); print $1}'",
    settings = function()
        widget:set_markup(markup(gray, " B ") .. output .. "  ")
    end
})


But could be better if we can detect the "plug".

When it's not plug: -> $ acpi
Battery 0: Discharging, 99%, 03:27:54 remaining

And when it's plug:

-> $ acpi
Battery 0: Full, 99%

Did you have an idea how to do it ?
Thanks for your support

**Comment by copycat-killer** [comment]
> I use awesome on linux on my macbookpro, not osx...

Ok, I thought you were on OSX because you specified that you have a Mac.

> Did you have an idea how to do it ?

You just need an if-then-else on your command output string, within settings function.

Right now I can't write it myself, I'll post updates tomorrow.

**Comment by dummys** [comment]
If you type this : acpi | cut -d, -f 2,3| awk ' {print $1 $2}' 

Did you have the same output as mine ?

**Comment by dummys** [comment]
Here is my stuff:
Must work on every computer, every hardware, and with multiple battery.
bat.lua
```lua

--[[

     Licensed under GNU General Public License v2
      * (c) 2013,      Luke Bonham
      * (c) 2010-2012, Peter Hofmann

--]]

local newtimer     = require("lain.helpers").newtimer
local first_line   = require("lain.helpers").first_line
local read_pipe    = require("lain.helpers").read_pipe

local naughty      = require("naughty")
local wibox        = require("wibox")

local setmetatable = setmetatable
local tonumber     = tonumber

-- Battery infos
-- lain.widgets.bat
-- Require acpi

local function worker(args)
    local bat = {}
    local args = args or {}
    local timeout = args.timeout or 30
    --could be multiple battery, like on lenovo
    local battery = args.battery or "BAT0"
    local notify = args.notify or "on"
    local settings = args.settings or function() end

    bat.widget = wibox.widget.textbox('')

    bat_notification_low_preset = {
        title = "Battery low",
        text = "Plug the cable!",
        timeout = 15,
        fg = "#202020",
        bg = "#CDCDCD"
    }

    bat_notification_critical_preset = {
        title = "Battery exhausted",
        text = "Shutdown imminent",
        timeout = 15,
        fg = "#000000",
        bg = "#FFFFFF"
    }

    function update()
        bat_now = {
            status = "Not present",
            tot = 1
        }

        if string.find(battery, "BAT0")
        then
            local cmd = "acpi | awk 'NR==1"
        else
            local cmd = "acpi | awk 'NR==2"
        end
        local cmd_status = "acpi | awk 'NR==1" .. "{print $3}' | tr -d ,"
        local present = read_pipe(cmd_status)

        if string.find(present, "Discharging")
        then
            bat_now.status = "Discharging"
            cmd_tot = "acpi | awk 'NR==1" .. "{print $4}' | tr -d %,"
            bat_now.tot = tonumber(read_pipe(cmd_tot))
        else
            bat_now.status = "Plug"
        end

        widget = bat.widget
        settings()

        -- notifications for low and critical states
        if bat_now.status == "Discharging" and notify == "on"
        then
            if bat_now.tot <= 15
            then
                bat.id = naughty.notify({
                    preset = bat_notification_low_preset,
                    replaces_id = bat.id,
                }).id
            elseif bat_now.tot <= 5
            then
                bat.id = naughty.notify({
                    preset = bat_notification_critical_preset,
                    replaces_id = bat.id,
                }).id
            end
        end
    end

    newtimer(battery, timeout, update)

    return setmetatable(bat, { __index = bat.widget })
end

return setmetatable({}, { __call = function(_, ...) return worker(...) end })

```

rc.lua 
```lua
-- Battery
 batwidget = lain.widgets.bat({
     settings = function()
         bat_tot = bat_now.tot
         bat_stat = bat_now.status
         if bat_stat == "Plug" then bat_tot = "Plug" end

         widget:set_markup(markup(gray, " B ") .. bat_tot .. " ")
     end
})
```

**Comment by copycat-killer** [comment]
I can't accept this, it introduces `acpi` as dependency.

Use `lain.widgets.base` as I told you. I'll try to investigate about the original `bat` widget later.

**Comment by aajjbb** [comment]
I don't have enough expertise to point whether acpi has an more accurate feedback on battery status than reading from */sys/class/power_supply* but, if I'm not mistaken, acpi doesn't come but default on most distributions (at least in manjaro which I'm using) and @copycat-killer is against any non default dependency on project.

**Comment by ff2000** [comment]
On Tue, 29 Dec 2015 10:43:30 -0800, Jeferson Lesbão de Siqueira <notifications@github.com> wrote:
> I don't have enough expertise to point whether acpi has an more accurate feedback on battery status than reading from */sys/class/power_supply* but, if I'm not mistaken, acpi doesn't come but default on most distributions (at least in manjaro which I'm using) and @copycat-killer is against any non default dependency on project.

Gentoo user here and acpi is not installed by default.

**Comment by dummys** [comment]
Ok, I understand. Then I will keep the widgets for me.
