### ISSUE TITLE
[solved] Battery percentage can be more than 100%

### ISSUE THREAD

**Issue by JJK96** [copycat-killer/lain#158]
The bat widget shows percentages up to 121%. I looked at the code for the widget and saw that there is a catch for that, so this should not be possible. 

Also I suggest to use the /sys/class/power_supply/BAT0/capacity file to get the capacity directly instead of using three files and then working out the capacity manually.

**Comment by aajjbb** [comment]
I can confirm that it happens with me as well. I [pulled](https://github.com/copycat-killer/lain/pull/159) a small patch to fix it.

**Comment by copycat-killer** [comment]
@JJK96 Check #160

**Comment by aajjbb** [comment]
Can you reproduce this problem with the new patch @JJK96 ? I'm not able to reproduce it because it used to happen in an aleatory manner. I think #161 finally fixed. Maybe this issue can be closed now.

**Comment by JJK96** [comment]
sorry for my late reaction, I just tested the new patch and it fixed the issue, it can be closed.

**Comment by copycat-killer** [comment]
Don't rename it, you can close it yourself.
