### ISSUE TITLE
bat.lua: 104 bad argument #2 to 'format'

### ISSUE THREAD

**Issue by avarx** [copycat-killer/lain#162]
I get 
`bat.lua:104: bad arguments #2 to 'format' (number has no integer representation)`
with the Multicolor Theme.
Please tell me what information's helpful for you.

**Edit**
*Macbook Air
*I'm using Arch.
*My file's named BAT0

thx & cheers

**Comment by aajjbb** [comment]
Are you using the last version of lain ?

**Comment by avarx** [comment]
thx for your answer. Yes I am using the latest version.

**Comment by aajjbb** [comment]
Sorry for the late reply, I'll check it right away.

**Comment by aajjbb** [comment]
Hi, which distribution are you using ?

Could you please post what does this files below contains when this issue happens ?

BAT1 = should be the name your distribution calls the battery. It's usually BAT0 or BAT1.

*/sys/class/power_supply/BAT1/capacity*
*/sys/class/power_supply/BAT1/energy_now*
*/sys/class/power_supply/BAT1/energy_full*

**Comment by avarx** [comment]
>/sys/class/power_supply/BAT1/capacity
doesn't matter: Error from 0 to 100.
Now: **8**
>/sys/class/power_supply/BAT1/energy_now
does not exist. I have **charge_now**:
Now: **462000**
>/sys/class/power_supply/BAT1/energy_full
does not exist. I have **charge_full**:
Now: **5271000**

**Comment by aajjbb** [comment]
#163 fixed it, although this error you reproduced should only happen when lain isn't able to open "/sys/class/power_supply/BAT1/capacity" file or it's content isn't an plain integer number. The secondary check seems unclear to me *(rem / tot) * 100)*, I think @copycat-killer could check if everything is okay with this expression.

**Comment by avarx** [comment]
Thanks again for your effort. It looks like you edited an old version.

**Comment by aajjbb** [comment]
An old version ? Afaik my fork is synchronized with the upstream lain, maybe I did something wrong in the pull request, can you point it to me ?

**Comment by avarx** [comment]
I'm on mobile now. Can send it to you tomorrow. But I can't see e.g. line 102 from your commit on the current version in the repo and the same for my version.

**Comment by copycat-killer** [comment]
@avarx `git pull` latest commit and let me know.

**Comment by avarx** [comment]
- git hard reset
- awesome restart > same error, sorry.

**Comment by copycat-killer** [comment]
Are you sure a reset brought you to latest master commit? Please `git clone` from scratch, just to be sure.

**Comment by netmonk** [comment]
exactly the same issue on linux (fresh archlinux) awesome 3.5.6 and a git clone install of awesome-copycat and lain.

**Comment by copycat-killer** [comment]
@avarx, read my previous comment and let me know.

**Comment by avarx** [comment]
@copycat-killer, sorry for the wait. You were right, Issue's **solved**. Thank you for your help!

**Comment by razor-x** [comment]
@copycat-killer I have been getting this error for a while when my system is 100% and on AC power.

Seems like in my case it's due to [these lines](https://github.com/copycat-killer/lain/blob/1129e88960205b9193b0d8b1c9358acd9c8d27b0/widgets/bat.lua#L128-L131)

```lua
if rate_time < 0.01 then -- check for magnitude discrepancies (#199)
  -- when at 100%, rate_time = 0, so math.log10(rate_time) = infinity which is nan
  rate_time_magnitude = math.abs(math.floor(math.log10(rate_time)))
  rate_time = rate_time * 10^(rate_time_magnitude - 2)
end
```

I can avoid this if I change the check to
```lua
if rate_time < 0.01 and rate_time > 0 then -- check for magnitude discrepancies (#199)
```
