### ISSUE TITLE
Pulseaudio configuration

### ISSUE THREAD

**Issue by vivekiitkgp** [copycat-killer/lain#164]
Sorry but I cannot find the respective lua file for pulseaudio configuration. Am I missing something?

**Comment by aajjbb** [comment]
Do you mean you can't find *pulseaudio* widget. It is in *widgets/contrib* folder.

**Comment by vivekiitkgp** [comment]
It isn't unless I am missing something very obvious.

**Comment by aajjbb** [comment]
I didn't understand what are you missing ? Can you elaborate ?

**Comment by vivekiitkgp** [comment]
Which file corresponds to the pulseaudio config? Cause when I use the config as given in Wiki, no module found error is given.

```
❯ ls
tpbat  ccurr.lua  init.lua  kbdlayout.lua  moc.lua  redshift.lua  task.lua
```

**Comment by aajjbb** [comment]
You're right. PulseAudio exclusive widget seems to be gone, but it's still featured in the wiki. Since it's missing, you can create your PulseAudio like widget using the abase widget, I think there's an example of this use in the closed issues section.

**Comment by copycat-killer** [comment]
I've never implemented a pulseaudio widget, but this guy did. #157 

I'm going to check his work and pull it.

**Comment by MaksVal** [comment]
Sorry! This is  my mistake!

**Comment by copycat-killer** [comment]
PulseAudio widget is now available as a main widget.

Read the [wiki](https://github.com/copycat-killer/lain/wiki/pulseaudio) for the configuration.

If you have issues, reply back here.
