### ISSUE TITLE
Unmute alsa channel problem

### ISSUE THREAD

**Issue by zobi8225** [copycat-killer/lain#165]
Hi, 
When i want mute sond volume from awesome, it mute the Master channel AND the Speaker channel
When i want to unmute it, awesome unmute only Master channel (and not Speaker...)

Any idea ? (Sorry for my bad english)

**Comment by aajjbb** [comment]
Can I see your volume widget instance in *rc.lua*. You can choose with channel the widget controls using the *channel* parameter.

**Comment by zobi8225** [comment]
Yep, all is here :
https://github.com/zobi8225/dot-stuff/blob/master/rc.lua

**Comment by copycat-killer** [comment]
> Any idea ?

Yes, read the wiki.

**Comment by copycat-killer** [comment]
But in spite of my bluntness, if you have any other related question, you can reply here.

I had to close it because it's not an issue.

**Comment by zobi8225** [comment]
it is ok.
Thanks.
