### ISSUE TITLE
pulseaudio: grep cmd not working

### ISSUE THREAD

**Issue by vivekiitkgp** [copycat-killer/lain#168]
Doesn't seem to work when there are more than one channels.

I can try fixing this if that's not an issue.

**Comment by copycat-killer** [comment]
Elaborate more on "work reliably" please

**Comment by vivekiitkgp** [comment]
Ah allright. It doesn't work when there are more than one channels. Using the default config in the Wiki throws errors when trying to use related functions, mute/unmute won't work, neither the volume up/down.

**Comment by copycat-killer** [comment]
Ok, but I was hoping for some stderr output or at least a screenshot.

There is no default config: the wiki only shows you how to call the widget, you have to feed it with an input table.

Try defining your sink number like this:
```lua
volumewidget = lain.widgets.pulseaudio({
    sink = #yoursink,
    settings = function()
        widget:set_text(volume_now.left) -- stub, set it as you like
    end
})
```

If this doesn't work, give me the output of `pactl info` and `pacmd list-sinks`.

**Comment by copycat-killer** [comment]
@vivekiitkgp Come on, let's solve this.

**Comment by vivekiitkgp** [comment]
In pulseaudio.lua, (https://github.com/copycat-killer/lain/blob/master/widgets/pulseaudio.lua#L28) we have
```
 pulseaudio.cmd = args.cmd or string.format("pacmd list-sinks | grep -e 'index: %d' -e 'volume: front' -e 'muted'", pulseaudio.sink)
```
The `pacmd` command when run on my computer, returns:
```
	muted: no
* index: 1
	muted: no
```
This output is incorrectly parsed by the matchers in the `pulseaudio.update()` function, thereby providing use with incorrect values to work with in the settings (showing a volume text or percentage, for example).

However, as you mentioned before, one can provide a custom `pactl` command to be used by the plugin. But that will require one to rewrite corresponding `pulseaudio.update()` function as well. At least, that is what I had to do.

Also, one can also use grep-magic to find out default sink without having the user to find out and provide manually.

Finally, in the pulseaudio wiki, the `%`s have to be escaped.

**Comment by copycat-killer** [comment]
> However, as you mentioned before, one can provide a custom `pactl` command to be used by the plugin. But that will require one to rewrite corresponding `pulseaudio.update()` function as well. At least, that is what I had to do.

There's no need to modify the widget, if ensure that your custom command outputs something like this:

```shell
	volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	muted: no
```

> Also, one can also use grep-magic to find out default sink without having the user to find out and provide manually.

That would require a pipe between `pactl` and `pacmd`, with some *grep-magic* as well. But these commands output text which is often translated in local language, so I should use wildcards, but `grep` doesn't support wildcards on most platforms. Then I could try using only the word "ink" for matching both "Default sink" and local language translation (which, for instance, in my case is "Sink predefinito") with something like this:

```shell
pacmd list-sinks | grep -e $(pactl info | grep -e 'ink' | cut -d' ' -f3) -e 'volume: front' -e 'muted'
```

But there's no warranty it's going to work for every system.

And that's why I wanted to keep it simple: instead of overburden the widget, the user can find it out in a couple of seconds. 

> Finally, in the pulseaudio wiki, the %s have to be escaped.

Can you be clear? Which "%s" are you referring to?

-----------------
**But most importantly**, you didn't 

 > give me output of `pactl info` and `pacmd list-sinks`

so either you give me that, or show me your modifications.

**Comment by vivekiitkgp** [comment]
> if you ensure that your custom command outputs something like this:

Yes I understand. But how do I do that? It is not trivial for me. Probably, not for many others as well. Some note in the Wiki would have been helpful.

> Can you be clear? Which "%s" are you referring to?

```
"pactl set-sink-volume %d -- +1%"
-- should be "pactl set-sink-volume %d -- +1%%"
```

> either you give me that

https://gist.github.com/3792746bcfb19dafd279

> show me your modifications.

Finally resorted to using ALSA widget.

**Comment by copycat-killer** [comment]
The problem is simple, you have `0/1:` instead of `front-left/front-right`.

Try with commit eb96149.

**Comment by vivekiitkgp** [comment]
Thanks. I tried that before. However, the volume picked up is not from the right sink but from first sink, which is not the default. I stopped at this point.

**Comment by copycat-killer** [comment]
And you tried my commit as well?

**Comment by vivekiitkgp** [comment]
Yes.

On Sat, 20 Feb 2016 3:42 pm Luke Bonham <notifications@github.com> wrote:

> And you tried my commit as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/copycat-killer/lain/issues/168#issuecomment-186563511>
> .
>
-- 
https://vivekiitkgp.github.io
GPG Key: 820BA5F1

**Comment by copycat-killer** [comment]
Then I guess the problem is only related to `grep` command, which is very platform-dependent, as I told before (and that's why we also have a `cmd` argument).

Please give me the output of this command:
```shell
pacmd list-sinks | sed -n -e '/base volume/d' -e '/index: 1/p' -e '/volume:/p' -e '/muted:/p' | sed -n -e '/index: 1/,+2p'
```
it should be something like this:
```shell
  * index: 1
	volume: 0:  69% 1:  69%
	muted: no
```

**Comment by vivekiitkgp** [comment]
On Sat, Feb 20, 2016 at 4:16 PM, Luke Bonham <notifications@github.com>
wrote:

> pacmd list-sinks | sed -n -e '/base volume/d' -e '/index: 1/p' -e '/volume:/p' -e '/muted:/p' | sed -n -e '/index: 1/,+2p'
>
>
Yes. The output matches the one you showed. Should work.

--
https://vivekiitkgp.github.io

**Comment by copycat-killer** [comment]
Very well, I modified the widget and updated the wiki to cover this case.

Can you please try the widget a last time?

**Comment by copycat-killer** [comment]
Confirmed working by #169.
