### ISSUE TITLE
Calendar: today highlight on Mar 1

### ISSUE THREAD

**Issue by shmilee** [copycat-killer/lain#174]
```
[$] date
Tue Mar  1 21:59:40 CST 2016
```
![deepinscrot-5911](https://cloud.githubusercontent.com/assets/2681740/13429112/8a1bf8b4-dff9-11e5-8125-8daccc0fc1ad.png)
![deepinscrot-1341](https://cloud.githubusercontent.com/assets/2681740/13429386/f513711e-dffa-11e5-836e-b6f496c30049.png)

Some information:
```
Name            : lain-git
Version         : 1235.1738f98-1

-- Calendar
lain.widgets.calendar:attach(mytextclock, {font = 'Ubuntu Mono', followmouse = true})
```

**Comment by shmilee** [comment]
When today=2,1,6,20,16:
https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L55
Maybe, we can replace 'space+today+space' with 'space +highlight today+space'.
```
f = io.popen(string.format("%s -e '3,/%d/ s/ %d / <b><span foreground=\"%s\" background=\"%s\">%d<\\/span><\\/b> /'",
                     init_t, today, today, calendar.bg, calendar.fg, today))
```
![deepinscrot-4852](https://cloud.githubusercontent.com/assets/2681740/13430587/a32af204-e000-11e5-9796-5a2a007d7bcb.png)

When today<10, 'highlight(space+today)+space' is better than space +highlight today+space'?

**Comment by copycat-killer** [comment]
LoL, forgot the spaces. :baby:

Try latest commit.

**Comment by shmilee** [comment]
How to deal with 13,20,17? 
No space before them. --> '13+space'. But we have two '16+space' . 
So why not let sed start from line 3 to match 'today+space'?
But 'today+space' is bad for highlight.

Maybe:
When today<10, 'space+today+space' works fine, although 'today' is sunday.
When today>=10, use 'today+space' or 'today', if we start from line 3.

**Comment by copycat-killer** [comment]
Again, try latest commit.

**Comment by shmilee** [comment]
That works well. Thank you.
