### ISSUE TITLE
bat.lua - watt is being computed wrongly

### ISSUE THREAD

**Issue by andering** [copycat-killer/lain#177]
Hello, 
correct me if i'm wrong 
but it seems to me that with widget bat.lua and his property watt (current Watt usage?), 
is being computes as **W** = **I** * **V** , so W = power_now * voltage_now ,
BUT power_now doesn't contain **I** , but already current usage, so **W**

```
local rate  = first_line(bstr .. "/power_now") or first_line(bstr .. "/current_now")
local ratev = first_line(bstr .. "/voltage_now")

bat_now.watt = string.format("%.2fW", (rate * ratev) / 1e12)
```

Thank you for making it clear for me.

**Comment by aajjbb** [comment]
It makes sense. 

If _power_now_ is not available, then usually _current_now is, the fact is that _power_now_ is already measured in _uW_, but _current_now_ is in _uA_, so it has to be multiplied by _voltage_now_ to become in fact power in watts.

**Comment by stwa** [comment]
But what **if** `power_now` is available? It looks like **W = W * V** (according to the code snippet)

**Comment by andering** [comment]
Right, that was my point. If power_now is present, W is calculated wrongly.

**Comment by copycat-killer** [comment]
So if `power_now`, we take `rate` directly, otherwise we do the computation. Did I understand right?

@andering @stwa Please tell me if latest commit is ok.

**Comment by stwa** [comment]
See my commit, suggestion to calculate watt for battery.
Not sure about the time_rat, was it correct before?

**Comment by copycat-killer** [comment]
Your pull request was perfectly equivalent to my commit.

But I merged it anyway because it avoids to use a flag variable and so it uses less lines.

`time_rate` should be correct, as far as I can see.

@andering Give us your opinion.

**Comment by andering** [comment]
Yes now it looks OK,

time_rat should be ok in case we can count that we have one or both from these two options (energy_now, energy_full, power_now) or (charge_now, charge_full,current_now) because they use same units, **if they for some reason mix, it would come out with various results** :)

Only issue now is this
 
`bat_now.watt = string.format("%.2fW", ratep)`

units are in uW so it needs to be divided by 1e6 to get Watts

`bat_now.watt = string.format("%.2fW", ratep / 1e6)`

my version of module (more explanatory) is here [bat.lua](https://github.com/andering/lain/blob/master/widgets/bat.lua
) , but i removed things which i saw as unreasonable like checking for negative values.

**Comment by copycat-killer** [comment]
Please pull me your `bat.lua` as well.

It's easter and I am so lazy. :camel:

**Comment by andering** [comment]
#183

**Comment by copycat-killer** [comment]
#183 merged
