### ISSUE TITLE
bat widget - make AC state available

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#178]
Please consider:

https://gist.github.com/Unode/0e01be49c88df908f262

The patch allows:

```
batwidget = lain.widgets.bat({
    settings = function()
        ...
        elseif bat_now.ac_status == "1" then
            baticon:set_image(theme.widget_ac)
        ...
        widget:set_markup(" " .. bat_now.perc .. "% ")
    end
})
```
regardless of the state of the battery (present/absent, charging/discharging/unknown).

More details are mentioned on the commit message in the patch.

**Comment by copycat-killer** [comment]
Merged.

**Comment by Unode** [comment]
Hi Luke,

Line 55, it's `ac` instead of `ac_status`. As you renamed it on line 83 to simply `ac`.

Thanks

**Comment by copycat-killer** [comment]
Actually, line 83 is a typo.

Fixed.
