### ISSUE TITLE
full battery shows "N/A" for percentage

### ISSUE THREAD

**Issue by gajjanag** [copycat-killer/lain#199]
lain version: 6fd1eec
config: https://github.com/gajjanag/config_files/blob/master/awesome/rc.lua
laptop: Lenovo Y410P

When my bat_now.status is "Full", I should still be able to see bat_now.perc as 100. However, instead I get N/A.

This was not the case 6 months back where things were fine, have not run a git bisect yet though.

**Comment by M4he** [comment]
I just pulled the latest version of lain and I'm now also facing this issue on Debian 8.0 (Jessie) using Awesome WM v3.5.6, my device is a MacBook Air 5,2.

Once the battery charge reaches 100%, it says "N/A" for both percentage and remaining time as long as AC is plugged in.

**Comment by copycat-killer** [comment]
I'll investigate this ASAP.

**Comment by copycat-killer** [comment]
Please try 84005d1.

**Comment by KenanY** [comment]
I am also seeing this with

  - lain https://github.com/copycat-killer/lain/commit/84005d16a9c58f385434d3f2e97161ab764b3122
  - awesome 3.5.9

`git bisect` reports de03791b816b60acbfcb41476330142135ac4ac3 as the first bad commit:

```
de03791b816b60acbfcb41476330142135ac4ac3 is the first bad commit
commit de03791b816b60acbfcb41476330142135ac4ac3
Author: copycat-killer <dada@archlinux.info>
Date:   Mon Apr 11 09:38:56 2016 +0200

    #193: update iff rate > 0 and battery not full

:040000 040000 0315fae6b1bc2e36435009b898b15cbb29659e91 c706af1085ff8ab05e2281e83e2dc35645c78e67 M	widgets
```

**Comment by copycat-killer** [comment]
@KenanY if you read the commit, the change (starting from line 87) is just syntactic, not semantic. At least, that was the intention.

Try removing the `battery not full` check from that if:

```diff
 -- update {perc,time,watt} iff rate > 0 and battery not full
if ((rate_current and rate_current > 0) or (rate_power and rate_power > 0))
-    and bat_now.status ~= "N/A" and bat_now.status ~= "Full"
+    and bat_now.status ~= "N/A"
then
```

Tomorrow I'll investigate properly.

**Comment by copycat-killer** [comment]
@KenanY @gajjanag 
I really don't know how this happens, but I switched back to previous syntax. I'm not sure if this changes anything, but tell me how it goes.

**Comment by M4he** [comment]
@copycat-killer Still observing this with the latest commit. If it helps, here are the contents of all the values referenced in your widget's code while being on AC, having a full battery and "N/A" being displayed by your widget:

```
cat /sys/class/power_supply/BAT0/voltage_now         
8357000

cat /sys/class/power_supply/BAT0/power_now           
0

cat /sys/class/power_supply/BAT0/energy_now          
58940000

cat /sys/class/power_supply/BAT0/energy_full         
58940000

cat /sys/class/power_supply/BAT0/capacity            
100

cat /sys/class/power_supply/BAT0/status              
Full
```

The following files are non-existent:
```
/sys/class/power_supply/BAT0/current_now
/sys/class/power_supply/BAT0/charge_now
/sys/class/power_supply/BAT0/charge_full
```

Haven't had time to fully comprehend all the calculations in your code yet, maybe you are able to make use of those outputs.

**Comment by M4he** [comment]
Don't know if it's directly related but I noticed something else being off:
Since the `bat_now.time` field offered by the widget started to show completely random (incorrect) values recently, I simply replaced this with the `bat_now.status` field in my display now. Doing this, I happened to notice that the value of `bat_now.status` never seems to get updated once the widget is loaded even if I plug or disconnect the AC cord.

I assume the culprit is this line: https://github.com/copycat-killer/lain/blob/7bc886679daf7dea81838ab792c91a78ecdd4804/widgets/bat.lua#L95

If I got this right, the battery status only gets updated if the last status was neither `Charging` nor `Discharging` here. However, `bat_now.n_status` doesn't seem to get updated anywhere else in the code so it's stuck in those states and the exposed `bat_now.status` seems to be based on the stuck value as well.

**Comment by copycat-killer** [comment]
@gajjanag @M4he please try f769402

@twentytwoo tell me if this solves #203 as well

**Comment by gajjanag** [comment]
Sadly, this does not fix the issue.

**Comment by twentytwoo** [comment]
Still not working on mine, or the powerarrow-darker battery widget.

**Comment by copycat-killer** [comment]
@gajjanag @M4he @twentytwoo please try again with latest commit.

Note that copycat themes are updated as well.

**Comment by gajjanag** [comment]
Better, the percentage seems to work now. Thanks.

Time still shows N/A when plugged in and full, and more seriously, even when the battery is not full and charging.

The first case is not really problematic IMHO, as I can't think of an unambiguous value for the time in the case of a full, not discharging battery. The second case should ideally display the time left for charging.

**Comment by copycat-killer** [comment]
@M4he @gajjanag I updated the code in order to make it work with `Full` test case [posted previously](https://github.com/copycat-killer/lain/issues/199#issuecomment-223279400). 

Here it also works while charging/discharging.

Please update again to latest commit and tell me.

**Comment by gajjanag** [comment]
Time no longer displays N/A.

However, while charging, it displays "00:00" for the time. This seems to be the only bad case left for me.

**Comment by copycat-killer** [comment]
The `00:00` string should only appear for `Full` or empty status.

How is `bat_now.time` while discharging?

Can you please provide me a snapshot [like this](https://github.com/copycat-killer/lain/issues/199#issuecomment-223279400)?

**Comment by copycat-killer** [comment]
@gajjanag 
Can you please provide me a snapshot [like this](https://github.com/copycat-killer/lain/issues/199#issuecomment-223279400), while charging?

**Comment by gajjanag** [comment]
❯ cat /sys/class/power_supply/BAT1/voltage_now
12069000
❯ cat /sys/class/power_supply/BAT1/power_now
640710000
❯ cat /sys/class/power_supply/BAT1/energy_now
48620000
❯ cat /sys/class/power_supply/BAT1/energy_full
54190000
❯ cat /sys/class/power_supply/BAT1/capacity
89
❯ cat /sys/class/power_supply/BAT1/status
Charging

**Comment by copycat-killer** [comment]
@gajjanag 

There's your problem: that `power_now` is one order of magnitude larger than other variables.

It's very odd, because every variable should (and must) be in the same order, as assumed by the widget so far.

Check latest commit, please.

**Comment by copycat-killer** [comment]
I added a more general check for magnitude discrepancies.

It should be ok now, but let me know otherwise.

**Comment by mmequignon** [comment]
Remaining time is now inchoherent.
Acpi shows 
`Battery 0: Full, 100%
Battery 1: Discharging, 96%, 03:06:24 remaining
`

while widget's remaining time says  00:39

**Comment by copycat-killer** [comment]
@mmequignon 

Read #207, git pull latest commit, and let me know.

**Comment by mmequignon** [comment]
Yes, latest commit solves this.
Thank you !

**Comment by alexnguyen91** [comment]
Hello, I don't want to create a new issue for the same problem so I'm gonna post it here.
The story is I'm using Asus K555L, when my battery is fully charge and AC is plugged in I got N/A as battery percentage (I'm using Multicolor theme), here is the information from uevent:

arch» cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=20
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=7600000
POWER_SUPPLY_VOLTAGE_NOW=7600000
POWER_SUPPLY_POWER_NOW=0
POWER_SUPPLY_ENERGY_FULL_DESIGN=37331000
POWER_SUPPLY_ENERGY_FULL=35666000
POWER_SUPPLY_ENERGY_NOW=35294000
POWER_SUPPLY_CAPACITY=98
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=ASUS Battery
POWER_SUPPLY_MANUFACTURER=ASUSTeK
POWER_SUPPLY_SERIAL_NUMBER=

As you can see there is no current_now value in there, also the power_now value is 0, which mean it will not pass this condition in bat.lua
`if bat_now.status ~= "Full" and (sum_rate_power > 0 or sum_rate_current > 0) then`
nor this
`elseif bat_now.status == "Full" then`

My lain version is 9e78c8d, of course this is trivial, but could we have another condition to check this case ?

**Comment by copycat-killer** [comment]
@alexnguyen91
Your `uevent` says `discharging`, while you said it should be `full` and on AC. 

If your information is right, then there's a system incoherence.

The battery widget relies on `power_supply` files, which are insufficient in this case, therefore the `N/A` values.

How do you think we can catch this condition, and more importantly, calculate the values correctly?

**Comment by alexnguyen91** [comment]
@copycat-killer
I think the `full` state of the battery can't happen all the time as the battery will have some electricity leak, for example my battery can be charged from 10% to 100% but then it will stop charging while slowly reducing to 95% and then continue to charge to 100% if I still keep the AC plugged.

My situation above could be explained like this:
- My AC is plugged so I have `Plug` showed in wibox
- My battery status is `discharging` even AC plugged because I have >95% power and my laptop won't charge it to prevent stress to the battery, result in POWER_NOW=0 (no electricity in or out the battery)

How about we add this check:
```
elseif bat_now.status ~= "Full" and sum_rate_power == 0 and bat_now.ac_status == 1 then
    bat_now.perc  = math.floor(math.min(100, (sum_energy_now / sum_energy_full) * 100))
    bat_now.time  = "00:00"
    bat_now.watt  = 0
```
Not sure if `bat_now.ac_status == 1` is needed

**Comment by copycat-killer** [comment]
Since you can reproduce the case, I suggest you to add the check yourself, test it for a while, then report back.

**Comment by alexnguyen91** [comment]
So far it's working fine for my laptop and my other Asus laptop, not sure about other brand.

**Comment by copycat-killer** [comment]
OK, I'm adding the patch. I'll work with my laptop tomorrow the whole day, so I feel confident that I'll catch possible issues.
