### ISSUE TITLE
Pulseaudio bar?

### ISSUE THREAD

**Issue by mnivoliez** [copycat-killer/lain#200]
Hello,

I wonder if a widget like a pulse audio bard could be possible or if the alsabar could be use to launch pavucontrol instead of amixer?

Best,

mnivoliez

**Comment by copycat-killer** [comment]
The answer is yes for both questions.

Download [pulsebar](https://gist.github.com/copycat-killer/2245bd57f35b9845634c7c10e4820578) into `lain/widgets`, and use it just like alsabar (same configs):

```lua
volume = lain.widgets.pulsebar()
```

**Comment by mnivoliez** [comment]
Awesome, thank you. ;)
