### ISSUE TITLE
bat_perc shows 100% when bat_now.perc == "N/A", instead of AC

### ISSUE THREAD

**Issue by twentytwoo** [copycat-killer/lain#203]
Using awesome v3.5.9 (Mighty Ravendark)
When bat_now.perc == "N/A" i.e, battery is charging, the output stays as 100%, instead of AC expressed in my below widget, I also tried to replicate it; successfully, using the awesome-copycats powerarrow-darker battery widget, which I know has an AC battery display widget, since it's shown in the screenshot, even when using that unmodified theme, the output is still shown as 100%. instead of AC when the charger is connected

I also noticed the same output when I used 

- `bat_now.ac_status == "1"`
- `bat_now.status == "Charging"`

in place of `bat_now.perc == "N/A"`

Here's my widget:
```lua
-- Battery baticon
baticon = wibox.widget.imagebox(beautiful.widget_bat)
batwidget = lain.widgets.bat({
    settings = function()
        if bat_now.perc == "N/A" or bat_now.ac_status == "1" then
            perc = "AC"
            baticon:set_image(beautiful.widget_ac)
        elseif bat_now.perc <= "75" then
            baticon:set_image(beautiful.widget_bat_med)
            perc = bat_now.perc .. "% "
        if bat_now.perc <= "50" then
            baticon:set_image(beautiful.widget_bat_low)
            perc = bat_now.perc .. "% "
        if bat_now.perc <= "25" then
            baticon:set_image(beautiful.widget_bat_no)
            perc = bat_now.perc .. "% "
        else
            perc = bat_now.perc .. "% "
        end
        end
        end
        widget:set_text(perc)
    end
})
```

**Comment by Arsakes** [comment]
The bug is still valid. You simply doesn't set bat_now.perc = 100% in case battery is full.
(The piece of code isn't invoked in case of full battery).
For fix: 
Check line 110 in bat.lua file.
Include if statement that checks if battery is full - if so - set bat_now.perc = 100%

PS: I've send you an e-mail asking about icons for halo theme :)

**Comment by copycat-killer** [comment]
Closed by cda6ec9.

**Comment by twentytwoo** [comment]
Alright I pulled the new version and updated my widget but it's still not working for me, 

```
[mktt@/s/d/L/L/P/p/BAT0]> pwd
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0
[mktt@/s/d/L/L/P/p/BAT0]> cat status 
Charging
...
[mktt@/s/d/L/L/A/p/AC]> pwd
/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/power_supply/AC
[mktt@/s/d/L/L/A/p/AC]> cat online 
1
```
I'm not sure if it's my widget now?

```
-- Battery baticon
baticon = wibox.widget.imagebox(beautiful.widget_battery)
batwidget = lain.widgets.bat({
    settings = function()
        if bat_now.status ~= "N/A" then
            if bat_now.ac_status == 1 then
                widget:set_markup(" AC ")
                baticon:set_image(beautiful.widget_ac)
                return
        elseif tonumber(bat_now.perc) <= 25 then
            baticon:set_image(beautiful.widget_bat_no)
        elseif tonumber(bat_now.perc) <= 50 then
            baticon:set_image(beautiful.widget_bat_low)
        elseif tonumber(bat_now.perc) <= 75 then
            baticon:set_image(beautiful.widget_bat_med)
        else
            baticon:set_image(beautiful.widget_bat)
        end
        widget:set_markup(" " .. bat_now.perc .. "% ")
    else
       baticon:set_image(beautiful.widget_ac)
    end
  end
})
```
Any ideas?

**Comment by copycat-killer** [comment]
I've just tried with powerarrow-darker battery widget, and it works.

I don't know what is your cause, so give me a snapshot of your battery files [like this one](https://github.com/copycat-killer/lain/issues/199#issuecomment-223279400).

**Comment by twentytwoo** [comment]
```
cat /sys/class/power_supply/BAT0/voltage_now         
17110000

cat /sys/class/power_supply/BAT0/power_now           
cat: /sys/class/power_supply/BAT0/power_now: No such file or directory

cat /sys/class/power_supply/BAT0/energy_now
cat: /sys/class/power_supply/BAT0/energy_now: No such file or directory

cat /sys/class/power_supply/BAT0/energy_full         
cat: /sys/class/power_supply/BAT0/energy_full: No such file or directory

cat /sys/class/power_supply/BAT0/capacity            
120

cat /sys/class/power_supply/BAT0/status              
Full
```

The files I do have in  /sys/class/power_supply/BAT0/ are:

- alarm
- capacity
- capacity_level
- charge_full
- charge_full_design
- charge_now
- current_now
- cycle_count
- device@
- manufacturer
- model_name
- power/
- present
- serial_number
- status
- subsystem@
- technology
- type
- uevent
- voltage_min_design
- voltage_now

**Comment by copycat-killer** [comment]
Give me a snapshot of the following:

* status
* capacity
* voltage_now
* charge_now
* charge_full
* current_now

**Comment by twentytwoo** [comment]
Here ya go:
```shell
cat status 
Discharging

cat capacity
95

cat voltage_now 
16536000

cat charge_now
2213000

cat charge_full 
2314000

cat current_now 
481000
```

**Comment by copycat-killer** [comment]
I tried your snapshot, and also modified it in order to have a `Full` status.

It's working correctly, so I assume the problem is not lain related.

Referring to the OP question, using **latest** powerarrow-darker battery widget template, you have `100%` instead of `AC` **only** if your identifier is not `AC0`, or you didn't set `ac`, or you set it wrongly. So, for instance, if you do

```shell
$ ls /sys/class/power_supply
```

and find `ACAD`, then set it like this in the widget:

```lua
mybat = lain.widgets.bat({
    ac = "ACAD",
    -- [...]
})
```

if it's not `ACAD`, it's something starting with `AC` anyway.

Let me know if this solves it.

**Comment by twentytwoo** [comment]
Yeah that was it, `ls /sys/class/power_supply` returned 'AC', thanks a lot for your help!

**Comment by twentytwoo** [comment]
Yeah that was it, `ls /sys/class/power_supply` returned 'AC', thanks a lot for your help!
