### ISSUE TITLE
Battery widget is miscalculating the time remaining

### ISSUE THREAD

**Issue by JLoureir0** [copycat-killer/lain#207]
Hi,

Haven't updated my awesome config in quite some time, but today I took a little bit to update it.
Everything is working like a charm except the battery widget, the bat_now.time tells me I have 300+ hours of remaining battery.

I took a look at old commits and the last one that is working for me is [this one](https://github.com/copycat-killer/lain/blob/726bf16543bd5a0e949aed7e59f9f4b967fdf123/widgets/bat.lua).

Another thing that happens, even with the commit above is that when the battery is charging the bat_now.perc is "N/A" instead of the value on the capacity file.

Here is the code in my rc.lua:

![image](https://cloud.githubusercontent.com/assets/2741968/16357440/91caf718-3aee-11e6-9ed3-6f0b2c65296d.png)

**Comment by copycat-killer** [comment]
Yes, I already noticed it, but I've waited to have a laptop close at hand before fixing it.

Basically, I was 1 order of magnitude off. It should be ok now.

I tried your widget with latest commit, and it's working without problems here.

Git pull master and check. If the problem persists, paste me a snapshot like [this](https://github.com/copycat-killer/lain/issues/199#issuecomment-227308846).

**Comment by JLoureir0** [comment]
Now the time is too small.
In the screenshot you can see in the right pane the output of upower where the time is correct.
I don't have all the files of that snapshot, I listed the ones I have in the left pane and printed out some.

![image](https://cloud.githubusercontent.com/assets/2741968/16357769/4cea8c0e-3af7-11e6-9775-90db0316e64c.png)

**Comment by copycat-killer** [comment]
It looks like N/A values are gone, good.

That time seems correct for a charging status. Did you wait for widget timeout, or restart awesome, before taking the screenshot? It's strange it doesn't update, that is, switch to discharging mode.

I'll give a look to your use case tomorrow. In the meantime, try replacing [this line](https://github.com/copycat-killer/lain/blob/master/widgets/bat.lua#L119) with [this other one](https://github.com/copycat-killer/lain/blob/726bf16543bd5a0e949aed7e59f9f4b967fdf123/widgets/bat.lua#L93).

**Comment by JLoureir0** [comment]
The N/A problem is good now, thank you.

The screenshot was taken with the laptop discharging (the 9 minutes are the discharge time), I did restart awesome and waited a bit but no change.

Thanks for taking the time :)

**Comment by JLoureir0** [comment]
The problem is the calculation of rate_power, since i don't have the file `power_now` it does the math with rate_power and rate current, but the result is too big.

`sum_rate_power = sum_rate_power + (rate_power or ((rate_voltage * rate_current) / 1e6))`

sum_rate_power = 24259014.0 <-- Too big!!
sum_rate_current = 2030000

On the line that it computes the rate_time it is dividing by the sum_rate_power that's why I am getting a small number as the remaining time.

`rate_time = sum_energy_now / (sum_rate_power or sum_rate_current)`

If I use the sum_rate_current instead of the sum_rate_power to calculate the rate_time it gives a better expected time until discharge.

**Comment by copycat-killer** [comment]
Yes. it should be `sum_rate_current` in your case.

Fact is, `sum_rate_power` is being used also for `watt` calculation. Let's introduce another variable just for that.

Check latest commit.

**Comment by JLoureir0** [comment]
Yep, it's fixed now :)

Thank you and keep the good work, love your themes.
