### ISSUE TITLE
bat.lua breaks when current_now isn't present

### ISSUE THREAD

**Issue by jdreaver** [copycat-killer/lain#208]
First of all, thanks for making this awesome library! I've been using it for years.

My battery doesn't have a `/current_now` file available for whatever reason. I noticed that you check [here](https://github.com/copycat-killer/lain/blob/master/widgets/bat.lua#L101) if `rate_current` is a null-value and just use zero instead. However, [here](https://github.com/copycat-killer/lain/blob/master/widgets/bat.lua#L104) `rate_current` is used without the check. This is where I get an error. I fixed this by changing `rate_current` to `(rate_current or 0)`.

I'm not exactly sure what commit caused this issue, but it looks like you are already aware that `/current_now` could be nonexistent. I would make a PR, but I don't have any sort of development environment set up for lua.

**Comment by copycat-killer** [comment]
Ok, I added safety check everywhere. Try latest commit.

**Comment by jdreaver** [comment]
I'm using this on Arch Linux from the AUR, so I'll have to wait for that to update (it should take less than a day). However, by looking at the commit I'm sure it's fixed. Thanks for the quick response!

**Comment by copycat-killer** [comment]
I've just updated the AUR package. Let me know.

**Comment by jdreaver** [comment]
I update and it works great, thanks!
