### ISSUE TITLE
Batt.lua not switching text to "A/C" after hitting 100%

### ISSUE THREAD

**Issue by Foxtrot** [copycat-killer/lain#210]
Hey again, it seems that now when the battery applet hits 100%, it does not switch to A/C like it used(?) to. ![Battery](http://i.imgur.com/4Hi73kP.png)

Restarting awesome will fix the issue.
![AC](http://i.imgur.com/8sUl1u6.png)

**Comment by copycat-killer** [comment]
Powerarrow-darker template shows `AC` when plugged, independently of percentage.

Do:

1. paste me your widget configuration, if it's different than default;
2. paste me `$ ls /sys/class/power_supply`;
2. try this widget, and when percentage is 100%, tell me what outputs before and after restarting:

```lua
-- Battery
baticon = wibox.widget.imagebox(beautiful.widget_battery)
batwidget = lain.widgets.bat({
    settings = function()
        naughty.notify({text = bat_now.status .. " " .. bat_now.ac_status, timeout = 20})
        if bat_now.status ~= "N/A" then
            if bat_now.ac_status == 1 then
                widget:set_markup(" AC ")
                baticon:set_image(beautiful.widget_ac)
                return
            elseif tonumber(bat_now.perc) <= 5 then
                baticon:set_image(beautiful.widget_battery_empty)
            elseif tonumber(bat_now.perc) <= 15 then
                baticon:set_image(beautiful.widget_battery_low)
            else
                baticon:set_image(beautiful.widget_battery)
            end
            widget:set_markup(" " .. bat_now.perc .. "% ")
        else
            baticon:set_image(beautiful.widget_ac)
        end
    end
})
```

**Comment by Foxtrot** [comment]
For future reference:
Widget:
```
-- Battery
baticon = wibox.widget.imagebox(beautiful.widget_battery)
batwidget = lain.widgets.bat({
    settings = function()
        if bat_now.perc == "N/A" then
            widget:set_markup(" AC ")
            baticon:set_image(beautiful.widget_ac)
            return
        elseif tonumber(bat_now.perc) <= 5 then
            baticon:set_image(beautiful.widget_battery_empty)
        elseif tonumber(bat_now.perc) <= 15 then
            baticon:set_image(beautiful.widget_battery_low)
        else
            baticon:set_image(beautiful.widget_battery)
        end
        widget:set_markup(" " .. bat_now.perc .. "% ")
    end
})
```

`/sys/class/power_supply` contents:
```
AC0  BAT0
```

**Comment by Foxtrot** [comment]
I just used the battery applet snippet from e5809ff in my existing rc.lua and now all is working well...

**Comment by copycat-killer** [comment]
That's the old template, that's why you have some discrepancies.

What you mean by e5809ff? It doesn't seem to be a lain commit.

**Comment by Foxtrot** [comment]
Sorry, I meant [this](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.powerarrow-darker).

**Comment by copycat-killer** [comment]
Ok, so when you update lain, be sure to update your `rc.lua` as well, if you stick with my templates.

Do your checks and let me know.

**Comment by Foxtrot** [comment]
Will do - thanks for the assistance!

**Comment by Foxtrot** [comment]
Ok, all seems to be working fine after updating the applet.

Thanks again and keep up the good work!:)
