### ISSUE TITLE
quakeconsole behaves differently depending on workspace

### ISSUE THREAD

**Issue by aviau** [copycat-killer/lain#219]
Hello!

quakeconsole behaves differently depending on what workspace I open it in. The size changes.

Note that I cannot reproduce this issue when I use xterm as my terminal.

For example:
Opening it in this workspace:
![screenshot from 2016-08-03 19-03-28](https://cloud.githubusercontent.com/assets/2706882/17384873/fdda63f8-59ac-11e6-83e0-e6af76f0b195.png)

Opening it in an empty workspace:
![screenshot from 2016-08-03 19-03-32](https://cloud.githubusercontent.com/assets/2706882/17384879/0127fc8c-59ad-11e6-8ab0-05bf82fff500.png)

quakeconsole config snippet:

```
  -- quake terminal
  local quakeconsole = {}
  for s = 1, screen.count() do
    quakeconsole[s] = lain.util.quake({ app = "guake", argname = "--name %s"})
  end
  -- }}}
```

**Comment by aviau** [comment]
Also, it looks like the new "remember last size" feature does not work with guake.

**Comment by aviau** [comment]
I really don't know what is related and what is not, but here is more info:
 - https://github.com/Guake/guake/issues/784

Sometimes, brigning up guake it will be scrolled down *below* the last line. This causes my terminal to be black. It seems to happen only when I force a height via rules.

**Comment by copycat-killer** [comment]
You're using a drop-down application with a drop-down container. That's nonsense.

Infact, this cannot happen with non drop-down application like `xterm`.

Read [here](https://github.com/copycat-killer/awesome-copycats/issues/117#issuecomment-237485248).
