### ISSUE TITLE
yawn failing

### ISSUE THREAD

**Issue by t0m5k1** [copycat-killer/lain#22]
when I use mod+w it displays the message "service not available at this moment"

http://i.imgur.com/3mpryRs.jpg
here are the lines for this widget i use in rc.lua

-- Weather
weathericon = wibox.widget.imagebox(beautiful.widget_weather)
yawn = lain.widgets.yawn(12752509, {
    settings = function()
        widget:set_markup(markup("#eca4c4", forecast:lower() .. " @ " .. units .. "°C "))
    end
})
<snip>
    right_layout:add(weathericon)
    right_layout:add(yawn.widget)

**Comment by kodyvajjha** [comment]
The widget is not working again. Showing a "Service not available at the moment" error. Also, the yahoo page http://weather.yahooapis.com/forecastrss?u=c&w=12752509 isn't showing the weather feed but is showing an OAUTH error. 

`curl --connect-timeout 3 -fsm 3 'http://weather.yahooapis.com/forecastrss?u=c&w=12752509'`
shows nothing.

I'm guessing the devs at Yahoo now need you to create a token etc to access the API data. 
Some info may be found [here](http://stackoverflow.com/questions/36186538/making-yahoo-weather-api-request-with-oauth-1).

Requesting a fix! I really love the weather widget and don't want it dying like this.
