### ISSUE TITLE
Battery widget shows wrong energy percentage for multiple batteries

### ISSUE THREAD

**Issue by monokles** [copycat-killer/lain#222]
Currently the battery widget determines the total energy percentage for multiple batteries by simply taking the average of all measured percentages. This works only when all batteries have the same capacity. This is not the case for all laptops.

What it should do is calculate the true percentage based on the sum of the current / max capacities of all batteries.

**Comment by copycat-killer** [comment]
Thanks for pointing this out. I don't have a multiple batteries latop.
