### ISSUE TITLE
Uninitialized value in bat.lua

### ISSUE THREAD

**Issue by neoflynn** [copycat-killer/lain#225]
Hello everybody, 

Yesterday i updated my lain package on my ArchLinux distro and this morning lain crashed at startup. Awesome reported me a nil value at line 67 in bat.lua `bat_now.n_perc[i] = 0`. To correct the problem i just declared the table before the loop : `bat_now.n_perc = {}`.

I hope this will help. :)

Bye.

**Comment by copycat-killer** [comment]
Thanks, but it has been already [reported](https://github.com/copycat-killer/lain/blob/master/widgets/bat.lua#L65) and [corrected](https://github.com/copycat-killer/lain/blob/master/widgets/bat.lua#L65). AUR package is updated too.

**Comment by neoflynn** [comment]
Oh ok sorry for the disruption...

Bye.

**Comment by copycat-killer** [comment]
No disruption at all. :hand:
