### ISSUE TITLE
quake start Xterm with default configure

### ISSUE THREAD

**Issue by PiraHzq** [copycat-killer/lain#228]
the rc.lua part about quake is bellow, but I start a xterm success with xterm default configure
```
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = terminal })
end
-- }}}

-- Dropdown terminal
awful.key({ modkey,	          }, "z",      function () quakeconsole[mouse.screen]:toggle() end),
```
something look like bellow
![2016-09-22-112559_725x670_scrot](https://cloud.githubusercontent.com/assets/5045503/18736243/ab15045c-80b7-11e6-94e2-f9956df5343a.png)

**Comment by copycat-killer** [comment]
You can set Xterm arguments in your `terminal` definition, or in `~/.Xresources`.

Look in `man xterm` for setting the background and the font.

Closing as unrelated.

**Comment by PiraHzq** [comment]
I has definition in `~/.Xresources`, but it does'nt work.@copycat-killer

**Comment by copycat-killer** [comment]
Then do
> set Xterm arguments in your `terminal` definition

After a quick peek at `man xterm`:

```lua
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = 'xterm -fa "Sans Mono:style=Book:antialias=false:pixelsize=14" -bg "#222222"' })
end
```

**Comment by PiraHzq** [comment]
Thanks @copycat-killer ,**set Xterm arguments in terminal** is work, but is there a way can make arguments in `~/.Xresources` work well ? I have many definition  with the color and font, write them all in a line is not a good idea...

**Comment by copycat-killer** [comment]
> is there a way can make arguments in `~/.Xresources` work well ?

Surely, but that's off-topic here and you have to find out by yourself. Google is your friend.
