### ISSUE TITLE
lain/widgets/calendar.lua:108: attempt to index a nil value (field 'font')

### ISSUE THREAD

**Issue by ionsquare** [copycat-killer/lain#229]
After cloning the copycat-killer repo in my ~/.config/awesome/ I tried to use the multicolor theme.

```
cd ~/.config/awesome/
cp awesome-copycats/rc.lua.multicolor rc.lua
```

When I restarted awesome I got an error about menugen not being found in rc.lua:112
I was able to fix that issue with this command: `ln -s /home/matthew/.config/awesome/awesome-copycats/menugen /usr/share/awesome/lib/menugen`.

When I restarted again though I got an error in calendar.lua:
```
Oops, an error happened!
/usr/share/awesome/lib/lain/widgets/calendar.lua:108: attempt to index a nil value (field 'font')
```
And another one with a stack traceback:
```
Oops, there were errors during startup!
error while running function
stack traceback:
    /usr/share/awesome/lib/lain/widgets/calendar.lu:108: in function 'lain.widgets.calendar.attach'
    /home/matthew/.config/awesome/rc.lua:136: in main chunk
error: /usr/share/awesome/lib/lain/widgets/calendar.lua:108: attempt to index a nil value (field 'font')
```
I'm on Arch Linux and everything is up to date as of today.

**Comment by ionsquare** [comment]
Apparently I'm an idiot (maybe the documentation is at least partly to blame as well).

The installation instructions for awesome-copycats says to use this command:
`git clone --recursive https://github.com/copycat-killer/awesome-copycats.git`

This creates a directory `awesome-copycats` which I assumed was necessary and expected. To fix the issue I had to move the contents up a directory, then everything worked fine. Also misleading error messages, those can take some blame as well.

**Comment by copycat-killer** [comment]
1. It is assumed that any user knows how awesome manages its files, before using this repository. If it's your first time, this requires a fast read from its wiki. Since now, this assumption was always met, but you're right: it's better to specify the point.

2. There's an [AUR package](https://github.com/copycat-killer/lain/wiki) for lain (by the way, in its wiki the git installation is fully clear).

**Comment by ionsquare** [comment]
1. Yes, I understand that and I know how to use Arch, but I assumed the 2 commands for install would be correct.
2. I did install lain from AUR. If I had installed it manually I probably would have made the connection about the paths sooner.

Thanks for putting the time into maintaining this, my desktop looks a whole lot better now.
