### ISSUE TITLE
bat widget, how to pass correct argument ?

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#237]
Hi,

I use bat widget like this:

```lua
-- Battery
batwidget = lain.widgets.bat({
     settings = function()
         ac = "AC"
         bat_perc = bat_now.perc
         if bat_now.ac_status == 1 then bat_perc = "Plug" end
         widget:set_markup(markup(gray, " Bat ") .. bat_perc .. " ")
     end
 })
```

My question is why my args ac is not used by the widget ?
Thanks

**Comment by copycat-killer** [comment]
Because you're using it wrongly. This is a correct usage:

```lua
-- Battery
batwidget = lain.widgets.bat({
     ac = "AC",
     settings = function()
         bat_perc = bat_now.perc
         if bat_now.ac_status == 1 then bat_perc = "Plug" end
         widget:set_markup(markup(gray, " Bat ") .. bat_perc .. " ")
     end
 })
```

Read the wiki for any other info, or check [awesome-copycats](https://github.com/copycat-killer/awesome-copycats) for some examples.

**Comment by dummys** [comment]
Oh missed the ,.
Ok thanks.

**Comment by copycat-killer** [comment]
You didn't miss the comma, you put an argument (`ac`) in the scope of another argument (`settings`).

The input must be a [table](https://www.lua.org/pil/3.6.html).
