### ISSUE TITLE
widgets/calendar.lua - Attempt to call a nil value (method 'connect_signal')

### ISSUE THREAD

**Issue by mbuelte** [copycat-killer/lain#242]
Hi, I just noticed a problem with the current changes in 'widgets/calendar.lua', running Awesome version v3.5.2-2174-g588cbc1.

> 
> error while running function!
> stack traceback:
> 	/usr/share/awesome/lib/lain/widgets/calendar.lua:119: in function 'lain.widgets.calendar.attach'
> 	$HOME/.config/awesome/rc.lua:246: in main chunk
> error: /usr/share/awesome/lib/lain/widgets/calendar.lua:119: attempt to call a nil value (method 'connect_signal')

After reversing calendar.lua to an commit before 44864dba370a427a67a6f4bf20ec9097bf5bde91 it is working again. Maybe there is an issue with my rc.lua and I'm using the library wrong?

Here is the line from the eror message:
> lain.widgets.calendar:attach(clock_widget, { font = "Terminus", font_size = 12 })

**Comment by paescuj** [comment]
You need to update your config - see https://github.com/copycat-killer/awesome-copycats/commit/6c2ca174217d2646632c99d4d110ec03061dc8f9.

**Comment by mbuelte** [comment]
Ah great! Thank you, it seems I lose touch with it recently. I'll upgrade my configuration.

**Comment by copycat-killer** [comment]
It's a subtle change in syntax, but a different concept in semantics.

Keep an eye on the wiki when you notice a meaty commit.
