### ISSUE TITLE
Is it possible to add a function to hide the titlebar with a key ?

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#244]
Hi,
Is it possible to create a bind to use for example "alt+b" to hide the tittlebar ?
I'm using the steamburn theme with your rc.lua.
Thanks.
Jon

**Comment by copycat-killer** [comment]
```lua
 -- Show/Hide Titlebars
awful.key({ altkey }, "b", function ()
    for _, c in pairs(awful.client.visible(mouse.screen)) do
        awful.titlebar.toggle(c)
    end
end),
```

[API reference](https://awesome.naquadah.org/doc/api/modules/awful.titlebar.html#toggle)

**Comment by dummys** [comment]
Thanks for this, but I was wrong, it's not the title bar I need to hide but the upper  bar where all the widget is and where is the name of the open window. what is the name of this bar ? I would like to hide this bar, for the tag and not clients.
Thnaks

**Comment by copycat-killer** [comment]
That's called `wibox`. There's [already a key binding to do that](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.steamburn#L403-L406) in default `rc.lua.steamburn`.

Hit `mod4 + b`.
