### ISSUE TITLE
helpers.lua:49: Invalid argument.

### ISSUE THREAD

**Issue by ghost** [copycat-killer/lain#25]
I get a `../awesome/lain/helpers.lua:49: Invalid argument` error popups when I turned off my wifi:

![2014-02-06-201021_1024x600_scrot](https://f.cloud.github.com/assets/3142116/2098208/29bcbb76-8f28-11e3-8cc9-83e86368f978.png)

**Comment by vojinc** [comment]
Hello everyone.I have a problem with lain widget net.lua.I use a powerarrow-darker in my Slackware linux on laptop.Everything work without a problem,my wifi eth work but widget for download and uploud don't work.When i start my OS first on screen show icon no_net.png.Thank you for  a cooperation.

**Comment by copycat-killer** [comment]
@vojinc 
Don't post in multiple thread. Your issue is treated in #102.
