### ISSUE TITLE
Pulsebar error with the color field

### ISSUE THREAD

**Issue by yaast** [copycat-killer/lain#251]
Alsabar in my setup currently works fine, my input for both alsabar and pulsebar is the same, and it has worked in the previous version.
All I change is the attributes common to both, such as width, height, and ticks.
Alsabar gives me no errors, but pulsebar gives me error in the pulsebar.lua file at line 150.
Using awesome 4.0 and your current lain git version, from the AUR.
Should I post the notification errors/logs?

EDIT: Comparing the Alsabar and Pulsebar files, the way colors are being set is different between the two.

**Comment by copycat-killer** [comment]
I've spotted the (distraction) error. Thanks.
