### ISSUE TITLE
lain-git package does not work with awesome 3.5.9 on archlinux

### ISSUE THREAD

**Issue by pmav99** [copycat-killer/lain#260]
not sure if problems with AUR packages are meant to be reported here, but anyway. 

Installing `lain-git` and adding `local lain=require("lain")` on `rc.lua` gives back a traceback. The culprit is [`gears.timer`](
https://github.com/copycat-killer/lain/blob/5d892e0ceb9d4dece6d2d61b2e5c4046bbc91e9f/helpers.lua#L12) which [does not exist in awesome 3.5.9](https://github.com/awesomeWM/awesome/tree/v3.5.9/lib/gears).

Not hard to checkout the correct version and rebuild the package, but I think that it would be useful if there was a git tag that would point people to the appropriate commit.

**Comment by copycat-killer** [comment]
This is a git package, the fault is only in the out-of-date official repository in archlinux. It has been flagged since almost a month, by now.

Anyway you're right, I'll write a warning.
