### ISSUE TITLE
[bat.lua] multiple batteries depends on the order of the list "batteries"

### ISSUE THREAD

**Issue by sim590** [copycat-killer/lain#261]
I have the following code in my `rc.lua` file:
```lua
baticon = wibox.widget.imagebox(beautiful.widget_battery)
batwidget = lain.widgets.bat({
    batteries = {"BAT0", "BAT1"},
    settings = function()
        if bat_now.perc == "N/A" then
            widget:set_markup(" AC ")
            baticon:set_image(beautiful.widget_ac)
            return
        elseif tonumber(bat_now.perc) <= 5 then
            baticon:set_image(beautiful.widget_battery_empty)
        elseif tonumber(bat_now.perc) <= 15 then
            baticon:set_image(beautiful.widget_battery_low)
        else
            baticon:set_image(beautiful.widget_battery)
        end
        widget:set_markup(" " .. bat_now.perc .. "% ")
    end
})
```

upower outputs this:
```sh
$ upower --dump | grep perc
    percentage:          100%
    percentage:          25%
    percentage:          59.7501%
```

and the percentage displayed is 100%. Now, if I supply the batteries array in the following order instead `{"BAT1", "BAT0"}`, the percentage will be accurate, i.e 59%. The issue comes from this line:
```lua
    bat_now.status = bat_now.n_status[1]
```

I won't comment on this as there are no words to describe my thoughts. I'm uploading a patch for this and hope you can merge it soon. Thanks.

**Comment by copycat-killer** [comment]
> I won't comment on this as there are no words to describe my thoughts.

Really?

I didn't assume that battery status is the first battery status. The variable `status` points to the first one for backwards compatibility with the old single battery API. Nothing less, nothing more.

Anyway, I recognize this may be convenient.

**Comment by sim590** [comment]
> > I won't comment on this as there are no words to describe my thoughts.
>
> Really?

@copycat-killer. I appologize. My comment was intended to be "funny", but I recognize there's no way that on the internet someone that doesn't know me can expect this. In reality, it is not funny and I appologize.

Tell me if I should change something in my patch.

**Comment by copycat-killer** [comment]
It's OK, no offence taken.

Thanks for the patch, I just have a single battery laptop, so I'd hardly thought about it.
