### ISSUE TITLE
Quake doesn't work with termite

### ISSUE THREAD

**Issue by codejunkienick** [copycat-killer/lain#269]
When I pass termite to quake and try to open it, all I see is loading cursor. Xterm at the same time works perfectly

**Comment by wimstefan** [comment]
Works here without a problem 
-> https://github.com/wimstefan/dotfiles/blob/master/config/awesome/rc.lua#L64-L76
-> https://github.com/wimstefan/dotfiles/blob/master/config/awesome/rc.lua#L693-L695

How do you call it?

**Comment by codejunkienick** [comment]
`    -- Quake application
    s.quake = lain.util.quake({ app = 'termite' })
`
`
    awful.key({ modkey, }, "z", function () awful.screen.focused().quake:toggle() end),

`

**Comment by copycat-killer** [comment]
Please read the [wiki](https://github.com/copycat-killer/lain/wiki/Utilities#quake) next time.
