### ISSUE TITLE
lain widgets not showing at all with awesome 4.0 

### ISSUE THREAD

**Issue by MaPePeR** [copycat-killer/lain#283]
**Please read the [wiki](https://github.com/copycat-killer/lain/wiki) and search the [Issues section](https://github.com/copycat-killer/lain/issues) first.**
Done

* output of `awesome -v` and `lua -v`
```
$ awesome -v; lua -v
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
```
* expected behavior and actual behavior

I come from awesomeWM/awesome/issues/1451 and first i thought i had a bigger problems with widgets, because i could not see the "keyboardlayout"-widget as well. But that was easily solvable by actually configuring multiple keyboard maps with `setxkbmap`. 

So i wanted to try the `bat` and `pulseaudio` widgets, but both did not show up for me at all. I also tried a `base`-widget with `cmd="echo Hello"`, which also did not show.

* steps to reproduce the problem

Install lain from AUR or with Git (i tried both). So my lain version should be up to date.
Change `rc.lua` to use a lain-widget ([Here are the changes](https://gist.github.com/MaPePeR/1b818283a808f9684502ff4179ffe45c)  i made on top of the default rc.lua file)
No lain widget visible.

**Comment by aajjbb** [comment]
Okay, I've never used the pulseaudio widget so I can't talk about this one, but about the battery one, you should set what the widget shows inside the `settings` function. 

Give a try to this version: 


    local batwidget = lain.widgets.bat({    
      settings = function()
         widget:set_text(" " .. bat_now.perc .. "% " .. bat_now.status .. " ")
      end
    })

**Comment by MaPePeR** [comment]
Oh. I was under the false assumption, that the default settings already show something...

The wikipage looks like this, so there might be room for improvement: 😉 
> Displays a notification when battery is low or critical.
> ```
> mybattery = lain.widgets.bat()
> ```
And this is what i used.

I guess its a similiar problem with pulseaudio. Sorry for bothering you. 

Sadly the bat widget does not work with my battery out of the box, so i guess i will have to figure something out.

**Comment by aajjbb** [comment]
The battery widget assumes that your battery is called `BAT0`. In case your battery has a different name:

    local batwidget = lain.widgets.bat({    
      batteries = { "My Battery Name" },
      settings = function()
         widget:set_text(" " .. bat_now.perc .. "% " .. bat_now.status .. " ")
      end
    })

**Comment by MaPePeR** [comment]
My battery is called `BAT0`. (I checked that default value for correctness in the first place ;) )

I think the problem is, that `power_now` does not exist.
```
ls /sys/class/power_supply/BAT0/
alarm               current_now   present        uevent
capacity            cycle_count   serial_number  voltage_min_design
capacity_level      device        status         voltage_now
charge_full         manufacturer  subsystem
charge_full_design  model_name    technology
charge_now          power         type
```

Also `status` returns `Unknown`... so my battery is probably not supported at all. ☹️

**Comment by copycat-killer** [comment]
@MaPePeR  The default (or rather, failsafe) `settings` doesn't set the widget, that's why nothing is shown.

The widgets have a main section where the [general usage](https://github.com/copycat-killer/lain/wiki/Widgets#general-usage) is explained. The bit you are citing from the wiki is only the widget signature, infact, just after that you can see the [input table](https://github.com/copycat-killer/lain/wiki/bat#input-table) section.

If you are missing some battery files, then read [here](https://github.com/copycat-killer/lain/wiki/bat#known-issues).

**Comment by copycat-killer** [comment]
Can you tell me which OS you are using?

**Comment by MaPePeR** [comment]
Yea, i've seen the input table but i missed the fact, that "empty function" means nothing is going to be shown. 

> If it takes a table, you have to define a function variable called settings in it, in order to make your customizations.

I've read it, but in my head i was still at the "trying it out to see what it does" step and did not want to make further customizations. My mistake. Sorry.

I'm using Arch Linux.

**Comment by copycat-killer** [comment]
Please, try the battery widget from the latest `lain` commit.

**Comment by MaPePeR** [comment]
After the `pull` the battery widget now shows a Percentage! great!

**Comment by frangio** [comment]
For the record, I read the wiki including the general usage section and I couldn't get any widget to work until I found this issue... It says:

> you have to define a function variable called settings in it, in order to make your customizations

It's not very clear that this step is necessary. "Customizations" sounds like something optional.

**Comment by copycat-killer** [comment]
@frangio 

With every widget library, you have to do that. Anyway, in the wiki main page I also wrote to notify every suggestion, since what might be clear to me might not be for others. I see you've edited the wiki yourself, so thank you.
