### ISSUE TITLE
btrfs support

### ISSUE THREAD

**Issue by vimalloc** [copycat-killer/lain#287]
It would be neat if the fs widget supported btrfs. The values returned by ```btrfs filesystem df /home``` can be very different then the values returned by ```df /home```, for example.

**Comment by copycat-killer** [comment]
I can't include btrfs, because it's not a standard like `df`. It's still premature and not widely adopted.

You could instead write an `abase` recipe, or an ad-hoc `contrib` widget.

**Comment by vimalloc** [comment]
btrfs is a standard (it was introduced into the kernel in 2009), and I would argue that it is no longer premature. That said, it hasn't been widely adopted at this point, so I totally understand why you wouldn't want to spend the time adding it to the fs widget.

I ended up going the abase route. I'll leave the code I'm using here, in case anyone else finds it useful:

```lua
myrootfs = lain.widgets.abase({                                                    
    timeout = 600,                                                                 
    cmd = "btrfs filesystem df /",                                                 
    settings  = function()                                                         
        local total, used = string.match(output, "Data.*total=(%d+%.%d+)GiB.*used=(%d+%.%d+)GiB")
        local percent_used = math.ceil((tonumber(used) / tonumber(total)) * 100)
        widget:set_markup(" [/: " .. percent_used .. "%] ")                        
    end                                                                            
}) 
```

Cheers.

**Comment by copycat-killer** [comment]
Sorry, I meant to say `standard` as in `standard de facto`.

I added your snippet to abase [use case examples](https://github.com/copycat-killer/lain/wiki/abase#btrfs).
