### ISSUE TITLE
widget did not work

### ISSUE THREAD

**Issue by hcbraun** [copycat-killer/lain#293]
Hi,
some widget did not work for me. Had to apply this patch:

```
diff --git a/widgets/alsa.lua b/widgets/alsa.lua
index 8139d42..93c74cc 100644
--- a/widgets/alsa.lua
+++ b/widgets/alsa.lua
@@ -50,7 +50,7 @@ local function worker(args)
 
     helpers.newtimer(string.format("alsa-%s-%s", alsa.cmd, alsa.channel), timeout, alsa.update)
 
-    return alsa
+    return setmetatable(alsa, { __index = alsa.widget })
 end
 
 return setmetatable(alsa, { __call = function(_, ...) return worker(...) end })
diff --git a/widgets/cpu.lua b/widgets/cpu.lua
index f61e2cc..ee214ef 100644
--- a/widgets/cpu.lua
+++ b/widgets/cpu.lua
@@ -76,7 +76,7 @@ local function worker(args)
 
     helpers.newtimer("cpu", timeout, update)
 
-    return cpu
+    return setmetatable(cpu, { __index = cpu.widget })
 end
 
 return setmetatable(cpu, { __call = function(_, ...) return worker(...) end })
diff --git a/widgets/mem.lua b/widgets/mem.lua
index ff5816c..cdc0f9f 100644
--- a/widgets/mem.lua
+++ b/widgets/mem.lua
@@ -48,7 +48,7 @@ local function worker(args)
 
     helpers.newtimer("mem", timeout, update)
 
-    return mem
+    return setmetatable(mem, { __index = mem.widget })
 end
 
 return setmetatable(mem, { __call = function(_, ...) return worker(...) end })
diff --git a/widgets/pulseaudio.lua b/widgets/pulseaudio.lua
index 8e89ffd..2b1962c 100644
--- a/widgets/pulseaudio.lua
+++ b/widgets/pulseaudio.lua
@@ -53,7 +53,7 @@ local function worker(args)
 
    helpers.newtimer("pulseaudio", timeout, pulseaudio.update)
 
-   return pulseaudio
+   return setmetatable(pulseaudio, { __index = pulseaudio.widget })
 end
 
 return setmetatable(pulseaudio, { __call = function(_, ...) return worker(...) end })
diff --git a/widgets/temp.lua b/widgets/temp.lua
index 4d8a727..b85d20f 100644
--- a/widgets/temp.lua
+++ b/widgets/temp.lua
@@ -37,7 +37,7 @@ local function worker(args)
 
     helpers.newtimer("coretemp", timeout, update)
 
-    return temp
+    return setmetatable(temp, { __index = temp.widget })
 end
 
 return setmetatable(temp, { __call = function(_, ...) return worker(...) end })

```

**Comment by copycat-killer** [comment]
Citing related #288 so it does not get lost (I can't reopen a pull request).

@renatofdds I'm about to give up, it may be better to revert to the `setmetatable` template in widgets, and remove `helpers.make_widget_textbox`. What do you think? I wanted to avoid any user further customization, but after all it should not be my scope how to set them.

I'm also thinking to remove {text,image}box completely, and just return updaters.

**Comment by renatofdds** [comment]
@copycat-killer i think make_widget_textbox is a code smell and you should drop it, use only ```widget``` key on the widgets (without the metatable), and people would add it to the layouts and reference it directly (it's a breaking change), like so:

```
local label = lain.widgets.cpu({
			settings = function ()
				local text = ""
				if tonumber(cpu_now.usage) >= 10 then
					text = cpu_now.usage .. "% "
				end
				icon.visible = (string.len(text) > 0)
				widget.text = text
			end
	})**.widget**
	label:connect_signal("mouse::enter", tooltip)
```

**Comment by copycat-killer** [comment]
There's no need for a guru to see that the `setmetatable` trick doesn't work in 4.x like it did in 3.5.x.

I tried to avoid the breaking change, but I couldn't. So be it.

**Comment by copycat-killer** [comment]
OK, I did it. Please, do your tests.

I will update the wiki tomorrow.

Speaking of which, the wiki could be. People tend to [miss](https://www.reddit.com/r/awesomewm/comments/5pq86u/pulseaudio_volume_control_for_40/#dcttz1h) the widget [usage](https://github.com/copycat-killer/lain/wiki/Widgets#usage) section, plus I'd like to make the texts as clear as possible, so any help there is very appreciated.

**Comment by renatofdds** [comment]
Nice. Thank you very much!

**Comment by sprnza** [comment]
Hi there!
I'm fairly new to lua. Could you elaborate what advantages brings this change?

**Comment by copycat-killer** [comment]
No advantages whatsoever, it's to avoid issues with the Awesome new API.

**Comment by sprnza** [comment]
OK, Cool!

**Comment by copycat-killer** [comment]
And I enhanced the wiki as better as possible. Now is rusher-proof.

Closing.
