### ISSUE TITLE
After a while I get error of comparison nil in line 102 of fs.lua, I use the example code that you have in the wiki. 

### ISSUE THREAD

**Issue by conandoel** [copycat-killer/lain#298]
┌conandoel@Gaiden ~
└> env LC_ALL=C df -k --output=target,size,used,avail,pcent
Mounted on     1K-blocks      Used     Avail Use%
/dev             1799472         0   1799472   0%
/run             1803988      1068   1802920   1%
/               28728356  12505256  15913516  45%
/dev/shm         1803988        12   1803976   1%
/sys/fs/cgroup   1803988         0   1803988   0%
/tmp             1803988      5984   1798004   1%
/home          450766496 304813584 123032260  72%
/run/user/1000    360796         8    360788   1%
┌conandoel@Gaiden ~
└> 
this is the output

**Comment by conandoel** [comment]
The solution was to add env before LC_ALL=C df -k --output=target,size,used,avail,pcent

**Comment by copycat-killer** [comment]
Let's use `/usr/bin/env`.
