### ISSUE TITLE
Calendar widget's got broken

### ISSUE THREAD

**Issue by sprnza** [copycat-killer/lain#299]
Hi there!
Calendar widget complains to line #66 of calendar.lua. notification_preset table is not defined there.

**Comment by sprnza** [comment]
Just read the wiki.

**Comment by dummys** [comment]
Hi @sprnza same issue here but didn't found what was wrong regarding the Wiki.
I use Tamsyn font which seems to be monospaced...

**Comment by sprnza** [comment]
Hi @dummys ! Configuration string has been changed. To attach the calendar it must look like this
```
cal = lain.widgets.calendar({attach_to = {mytextclock}})
```

**Comment by dummys** [comment]
Oh yeah thx, Now I didn't get anymore the day we are bolded. Did you have the same issue ?

**Comment by sprnza** [comment]
Yep, see here #300

**Comment by dummys** [comment]
not working, got already the code in...
