### ISSUE TITLE
AUR package: recognize awesome branch 

### ISSUE THREAD

**Issue by qwelyt** [copycat-killer/lain#302]
Awesome
```
awesome v4.0-170-g6c248485-dirty (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```
Lua `Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio`

If you just install lain with the aur-package, it will not be found by Awesome. You get a big red popup with directories it tries to look in.

I had to symlink the lib to my local config.
```
ln -s /usr/share/awesome/lib/lain ~/.config/awesome/lain
```

**Comment by Raumzeitkeks** [comment]
```
$awesome -v
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```
Just installed lain through the [aur-package](https://aur.archlinux.org/packages/lain-git/) yesterday and updated it a minute ago. Tried it out with a [copycat-killer/awesome-copycats](https://github.com/copycat-killer/awesome-copycats) theme. Everything worked fine for me without symlinking.

**Comment by qwelyt** [comment]
So might be a change in Awesome upstream that's causing the issue then.

**Comment by copycat-killer** [comment]
@qwelyt can you unlink, restart X and reinstall, please?

**Comment by qwelyt** [comment]
@copycat-killer First thing I tried to do. Still got the problem.

**Comment by copycat-killer** [comment]
@qwelyt Maybe you're installing Awesome in `/usr/local/share`?

**Comment by qwelyt** [comment]
@copycat-killer Hm. You might be on to something.
```
qwelyt@machine ~ % which awesome
/usr/local/bin/awesome
```

**Comment by copycat-killer** [comment]
Download and install `lain-git` manually, but before doing `makepkg`, change [line 21](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lain-git#n21) in the PKGBUILD to

```shell
install -dm755 "$pkgdir/usr/local/share/awesome/lib/lain"
```

It should work.

The AUR package has to be updated to identify the correct awesome branch.

**Comment by copycat-killer** [comment]
AUR package has been updated.
