### ISSUE TITLE
task.prompt lets you enter any command

### ISSUE THREAD

**Issue by 2009** [copycat-killer/lain#304]
You can just enter any command e.g. `ls` and it will display the output.
Is this intended?

**Comment by copycat-killer** [comment]
Yes.

The code is meant to be simple, so you are also free to do injections or self-harm in any way you like.

**Comment by 2009** [comment]
Haha, no worried.
I was just a little confused when I first used it as expected to enter the task command e.g. `add "todo"` rather than `task add "todo"`.
