### ISSUE TITLE
Problem with awful.tooltip

### ISSUE THREAD

**Issue by wimstefan** [copycat-killer/lain#305]
* output of `awesome -v` and `lua -v`
awesome  (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0

Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

* expected behavior and actual behavior
- Expected: awesome starting up with my rc.lua as it did until last week
- Actual: awesome throws an error into the X log and falls back to the default awesome rc.lua

The error:
`error while running function!
stack traceback:
        /usr/share/awesome/lib/awful/tooltip.lua:457: in function 'add_to_object'
        /usr/share/awesome/lib/awful/tooltip.lua:596: in function </usr/share/awesome/lib/awful/tooltip.lua:502>
        (tail call): ?
        /home/swimmer/.config/awesome/rc.lua:240: in main chunk
error: /usr/share/awesome/lib/awful/tooltip.lua:457: attempt to call method 'connect_signal' (a nil value)`

The part in my rc.lua which is referred to:
```lua
local tooltip_mem = awful.tooltip({
  objects = { widget_mem },
  margin_leftright = 10,
  margin_topbottom = 10,
  shape = gears.shape.infobubble,
  timer_function = function()
  local title = "Memory &amp; swap usage"
  local used = pad_to_length(mem_now.used, mem_now.swapused)
  local swapused = pad_to_length(mem_now.swapused, mem_now.used)
  local text
  text = ' <span font="'..beautiful.mono_font..'">'..
         ' <span weight="bold" color="'..beautiful.fg_normal..'">'..title..'</span> \n'..
         ' <span weight="bold">-------------------</span> \n'..
         ' ▪ memory <span color="'..beautiful.fg_normal..'">'..used..'</span> MB \n'..
         ' ▪ swap   <span color="'..beautiful.fg_normal..'">'..swapused..'</span> MB </span>'
   return text
 end
})
```

* steps to reproduce the problem
If necessary I can also provide a gist with my actual rc.lua ...

**Comment by copycat-killer** [comment]
You're trying to access a table which is only in the scope of a widget.

This is a way to do it:

```lua
local my_mem_now -- a link to the table you want

local widget_mem = lain.widgets.mem({
    -- [...]
    settings = function()
        my_mem_now = mem_now
        -- [...]
    end
})

local tooltip_mem = awful.tooltip({
  objects = { widget_mem.widget },
  margin_leftright = 10,
  margin_topbottom = 10,
  shape = gears.shape.infobubble,
  timer_function = function()
  local title = "Memory &amp; swap usage"
  local used = pad_to_length(my_mem_now.used, my_mem_now.swapused)
  local swapused = pad_to_length(my_mem_now.swapused, my_mem_now.used)
  local text
  text = ' <span font="'..theme.mono_font..'">'..
         ' <span weight="bold" color="'..theme.fg_normal..'">'..title..'</span> \n'..
         ' <span weight="bold">-------------------</span> \n'..
         ' ▪ memory <span color="'..theme.fg_normal..'">'..used..'</span> MB \n'..
         ' ▪ swap   <span color="'..theme.fg_normal..'">'..swapused..'</span> MB </span>'
   return text
 end
})
```

**Comment by wimstefan** [comment]
Thanks a lot! At the end that solved my problems :smiley: 

It's really hard for a simple user like me to follow all the changes at the moment :wink:  All in a sudden things stop working which used to work and than it's hard to find what has changed precisely and how you have to reconfigure your settings if you're not a programmer. So I'm really thankful that you showed me the way through that jungle :sunglasses: 

BTW: Is that change from `beautiful.` to `theme.` just valid for lain or for awesome globally?

**Comment by copycat-killer** [comment]
> BTW: Is that change from beautiful. to theme. just valid for lain or for awesome globally?

It's valid only if you do your theming in `theme.lua`. Ignore that, and use `beautiful` if youre using this code in `rc.lua`.
