### ISSUE TITLE
Calendar doesn't have notification_preset set to naughty.config.defaults

### ISSUE THREAD

**Issue by sprnza** [copycat-killer/lain#306]
Hi there!
Wiki says it has but actually it doesn't.
line 101 must be altered this way (sorry IDK how to create patches) :)
```
calendar.notification_preset = args.notification_preset or naughty.config.defaults
```

**Comment by copycat-killer** [comment]
That would cause #290 again.

`naughty.config.defaults` is the implicit fallback. Or it isn't for you?

**Comment by sprnza** [comment]
Nope, why? I overrided it in my rc.lua in order to tweak all notifications. Maybe it's not correct to configure notifications like that. It's better to change naughty.config.presets.normal? Just have done like that don't see any difference :) 
Anyway the WIKI is wrong saying the default value of `notificaiton_presets` is `naughty.config.defaults`
Wouldn't #290 be solved if you just remove
```
fs.notification_preset      = naughty.config.defaults
```
as it is in calendar.lua?

**Comment by copycat-killer** [comment]
OK, updated wiki.

> Wouldn't #290 be solved if you just remove [...] as it is in calendar.lua?

That is removed already.
