### ISSUE TITLE
mpd: escape single quotes in finding cover path

### ISSUE THREAD

**Issue by yaast** [copycat-killer/lain#308]
Awesome Version:
```
awesome v4.0-172-g5439c347 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```
Lua Version:
`Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio`

In my music library, there are many types of .jpg  and .png and the widget picks almost all of them just perfectly.
Some however, I'm not sure why its not being picked up,
Across 4 different folders, all with cover.jpg files for the art, only 2 of them pick up the cover art for the notification, the other 2 just the artist/song is displayed in the notification.

**Comment by copycat-killer** [comment]
Probably there's something in the path, or some issue with the asynchronicity.

Can you give me a scrot of the culprit dirs structure? Maybe give me a zip (without the songs, of course, just the dirs with a placeholder cover inside.

**Comment by copycat-killer** [comment]
OK, continuing from IRC. Try replacing line 115 with this one:

```lua
local cover  = string.format("find '%s' -maxdepth 1 -type f | egrep -i -m1 '%s'", path:gsub("'", "\'"):gsub('"', '\"'), cover_pattern)

```

**Comment by yaast** [comment]
As requested, the folders in question.
[laintest.tar.gz](https://github.com/copycat-killer/lain/files/751501/laintest.tar.gz)

**Comment by copycat-killer** [comment]
@yaast It should be fixed now.

**Comment by yaast** [comment]
Yes its fixed, just updated it. All my songs are corretly displaying now! Thanks!
