### ISSUE TITLE
calendar: show only when mouse clicks

### ISSUE THREAD

**Issue by whooper2** [copycat-killer/lain#320]
Is it possible to change the calendar widget behaviour to show only when the mouse clicks on top of it? Instead of just when it's hovering over.
If yes, how would this be achieved?

**Comment by copycat-killer** [comment]
Fetch latest commit and disconnect `mouse::enter` signal from your widget like this:

```lua
yourwidget:disconnect_signal("mouse::enter", lain.widget.calendar.hover_on)
```

**Comment by whooper2** [comment]
Thanks!
