### ISSUE TITLE
Low battery notification

### ISSUE THREAD

**Issue by Antoine-H** [copycat-killer/lain#321]
Hello,

I recently updated to awesome 4 and therefore update my rc.lua. I use the multicolor theme.
For some reason, I can't get the battery notifications anymore.

I tried investigating and it seems that `type(bat_now.perc) == "number"` returns false.
When I output its type and value, I get `string` `6%`.

I can't understand why the '%' is stored in bat_now.perc. Is that normal?

Here is `lua -v`
```
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
```
Here is `awesome -v`
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

Thank you for your time, hope I can solve this.

Best,

**Comment by copycat-killer** [comment]
If you [read](https://github.com/copycat-killer/lain/wiki/bat) the wiki, you'll know that `bat_now` stores strings only, and if you [see](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/multicolor/theme.lua#L174-L187) the widget, the "%" is added by the multicolor template.

So everything is normal, and the fact that you read `6%` means that the widget is working.

See how you add the widget to the wibox: as you can read [here](https://github.com/copycat-killer/lain/wiki/Widgets#usage), the correct syntax is like `mybattery.widget`.

**Comment by Antoine-H** [comment]
Thanks for the explanation, it makes sense.
I haven't changed a lot, in fact the only thing I had to change was `BAT0` which in my case is `BAT1`.

Then, there is still a problem. If `bat_now.perc` is a string, I'm never going to get any low battery notification because of `type(bat_now.perc) == "number"` which will always return false. Or, am I missing something?

Would I need to write something like this?
```
if notify == "on" and bat_now.status == "Discharging" then
    bat_now_perc_int = tonumber(bat_now.perc:sub(1,-2))
    if bat_now_perc_int <= 5 then
        bat.id = naughty.notify({
            preset = bat_notification_critical_preset,
            replaces_id = bat.id
        }).id
    elseif bat_now_perc_int <= 15 then
        bat.id = naughty.notify({
            preset = bat_notification_low_preset,
            replaces_id = bat.id
        }).id
    end
end
```

**Comment by copycat-killer** [comment]
It should be a number there, I'll check and fix it tomorrow.

In the meantime, adding that snippet to `settings` should work.

**Comment by Antoine-H** [comment]
I added that snippet to `bat.lua`, it works but it's not very clean :)

**Comment by copycat-killer** [comment]
Should be done in a6ca6ab.
