### ISSUE TITLE
fs widget errors when used in a 2 monitor setup

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#322]
I have the following on my rc.lua:

    fswidget = lain.widget.fs({
        followtag = true,
        notification_preset = {
            fg = machine.theme.fg_focus,
            bg = machine.theme.bg_normal,
            font = machine.theme.font_name .. " " .. machine.theme.font_size,
        },
        settings  = function()
            widget:set_text(" " .. fs_now.used .. "% ")
        end
    })

which then gets used as part of:

    s.mywibox:setup {
        ...
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            ...
            fswidget,
            ...

This works fine on a 1 screen setup.

However it fails with 2 screens producing:

    stack traceback:
            /usr/share/awesome/lib/naughty/core.lua:324: in function 'set_timeout'
            /usr/share/awesome/lib/naughty/core.lua:500: in function 'notify'
            ...me/u/.config/awesome/modules/lain/widget/fs.lua:42: in function '?'
            /usr/share/awesome/lib/wibox/widget/base.lua:480: in function 'drill'
            /usr/share/awesome/lib/wibox/widget/base.lua:493: in function 'drill'
            /usr/share/awesome/lib/wibox/widget/base.lua:493: in function 'drill'
            /usr/share/awesome/lib/wibox/widget/base.lua:527: in function 'setup'
            /home/u/.config/awesome/rc.lua:398: in function 'func'
            /usr/share/awesome/lib/awful/screen.lua:395: in function 'connect_for_each_screen'
            /home/u/.config/awesome/rc.lua:371: in main chunk
    error: /usr/share/awesome/lib/naughty/core.lua:324: attempt to compare number with table

Inspecting the code of `widget/fs.lua` the problem seems to be that `fs.show()` is called with a `wibox.widget.textbox` as 1st argument.
So `seconds` is actually a table instead of a number.

I found this by inspecting (i.e. `print(seconds)`) the content of the argument `seconds`.
I don't understand what is calling the `fs.show()` method though.
I thought it would be https://github.com/copycat-killer/lain/blob/master/widget/fs.lua#L118 but changing this line had no effect.

On another note, there seems to be an issue around line https://github.com/copycat-killer/lain/blob/master/widget/fs.lua#L35 .
That is unless `notification_preset.screen` is supposed to be left undefined when neither `scr` nor `followtag` evaluate to true.
Line 36 also has `scr or 1`. The `or 1` will never happen given the `elseif` above.

* output of `awesome -v` and `lua -v`

    awesome v4.0 (Harder, Better, Faster, Stronger)
    • Compiled against Lua 5.1.5 (running with Lua 5.1)
    • D-Bus support: ✔
    • execinfo support: ✔
    • RandR 1.5 support: ✔
    • LGI version: 0.9.0

**Comment by Veratil** [comment]
Unode and myself have tried a few things. He said on IRC that changing Line 41 to:
`type(seconds) == "number" and seconds or 5`
made the error stop happening, but yet to see if the problem is resolved (he was running remote at the time).

**Comment by copycat-killer** [comment]
@Unode Every `lain` widget is a [table](https://github.com/copycat-killer/lain/wiki/Widgets#usage), to access the widget itself, you have to use the `widget` field. 

In your instance:

```lua
    s.mywibox:setup {
        ...
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            ...
            fswidget.widget,
            ...
```

Check if this is the cause of your `fs.show`.

> Line 36 also has scr or 1. The or 1 will never happen given the elseif above.

This should be solved by swtiching to `else`.

**Comment by Unode** [comment]
@copycat-killer Thanks I'll test this once I'm back to 2 screens but for now it seems like that's the issue.

I'm surprised that it was not a problem with 1 screen though.

**Comment by copycat-killer** [comment]
> I'm surprised that it was not a problem with 1 screen though.

It's surely an overflow: 

Lua is "able to fallback" to the first table entry if you don't specify it (a sort of implicit `setmetatable`), as long as the table type is instantiated only once.

**Comment by Unode** [comment]
This fixed it. Thanks
