### ISSUE TITLE
Marquee effect on mpd widget

### ISSUE THREAD

**Issue by Unode** [copycat-killer/lain#324]
Hi all,

When using the mpd widget and playing radios from online streams, sometimes the text printed is quite long causing other widgets to shrink to an almost ridiculous size (notably the tasklist).

With that said, 2 questions:
* Is there any way to limit the size of a widget such that it doesn't expand more than a given size, something like `maxwidth` (and why not a `minwidth` while we are at it)? 
* Would it be possible to implement a marquee effect [(wikimedia link)](https://upload.wikimedia.org/wikipedia/commons/a/ae/HTML_marquee.ogv) when there's more text than what can fit in the available space.

**Comment by copycat-killer** [comment]
> Is there any way to limit the size of a widget such that it doesn't expand more than a given size, something like `maxwidth` (and why not a `minwidth` while we are at it)? 

Yes: [`wibox.container.constraint`](https://awesomewm.org/doc/api/classes/wibox.container.constraint.html).

You can set both a minimum and a maximum dimension, also together (`exact`). A quick example:

```lua
local myexactwidth = 100
local mympdcontainer = wibox.container.constraint(wibox.widget { 
    nil, nil,
    mympd.widget,
    layout = wibox.layout.align.horizontal 
}, "exact", myexactwidth)
```

> Would it be possible to implement a marquee effect [(wikimedia link)](https://upload.wikimedia.org/wikipedia/commons/a/ae/HTML_marquee.ogv) when there's more text than what can fit in the available space.

I don't think it's currently possible, you should ask awesome devs, or submit a feature request to [awesome](https://github.com/awesomeWM/awesome).

**Comment by Unode** [comment]
@copycat-killer Seems like [there is something indeed](https://awesomewm.org/apidoc/classes/wibox.container.scroll.html) for such a marquee effect.

**Comment by Unode** [comment]
The [scroll effect](https://awesomewm.org/apidoc/classes/wibox.container.scroll.html) works both as a size constrained widget and scrolls the text within.

This works perfectly for me:

    local mpd = wibox.container.scroll.horizontal(mpdwidget.widget)
    mpd:set_fps(5)
    mpd:set_max_size(200)

A short note, mouse/button events should be bound to `mpd` instead of `mpdwidget.widget`.
According to @psychon clicks do not propagate.

**Comment by copycat-killer** [comment]
You anticipated me by some minutes. :)

Good to know.
