### ISSUE TITLE
How to: volume fade in toggling mpd

### ISSUE THREAD

**Issue by Pablo1107** [copycat-killer/lain#325]
After a little **research on the wiki and some forums** I know it's possible to **make mpd gradually reducing its volume** (hence the fade-out effect) **when pausing**. 

My question is: Did any of you _implement_ this in any way shape perform (even if it's not working properly) for the mpd widget to have a pausing mechanism more dynamically? 

I ask this because I'm on the edge of forking and trying to do it myself, but I have little knowledge about the source code and even C in all cases. I just studied C++ so I'm fresh with syntaxis, but of course C++ ≠ C.

Any ideas?
Thanks beforehand.

**Comment by copycat-killer** [comment]
Let me understand: what do you mean by a *more dynamically pausing mechanism*? Make an use case example.

**Comment by Unode** [comment]
@Pablo1107 there is a crossfading feature as part of mpd. I've used it in the past for transitions between songs.
From your description you probably want something like [this](http://guillaumeplayground.net/mpd-mpc-fade-in-out-script/). I'd say beyond the scope of the widget.

**Comment by copycat-killer** [comment]
If that is what he wants, then definitely it's beyond this widget.

Anyway, such script can be bounded to an [`awful.widget.watch`](https://awesomewm.org/doc/api/classes/awful.widget.watch.html).

**Comment by Pablo1107** [comment]
@copycat-killer thanks for replying personally, I enjoy very much your work and personally I built my awesomeWM based on one of your themes which makes it so much easier, I learned a lot of Lua in almost no time.

I did forget about making a _use case_ example but I will give a simple one to make my point. Suppose you want to pause a currently played song, -don't you get annoyed when pausing abruptly a good song?- you only have to do something like "Shift + Pause Button" in order to make fade-out effect in the pausing mechanism o even better make it the default behaviour in the config file. 

I think there is the use case I try to replicate, but nevertheless some other folk out here that likes my idea can of course use my source code for actually expand it a little bit more, I'm trying to go full _KISS_ in this proyect.

@Unode thanks for replying, I will give it a look when I have time.

@copycat-killer I didn't actually read whan @Unode sent me yet but I can almost guaranteed that such a mechanism is worth a look for a official repo, even though I can just fork it with your permission for making my own parts of the project and wait for you to see if you like it not.

I'll give a look at the resources you just gave me and tell you about it.
Thanks for the interest in the idea.

**Comment by Pablo1107** [comment]
Other thing I just recently asked myself, the project is called lain after _Serial Experiments Lain_ anime? haha
Just curious.

**Comment by copycat-killer** [comment]
@Pablo1107 

If you want a fade in/out in toggling `mpd`, just put [this script](https://gist.github.com/copycat-killer/76e315bc27c6cdf7edd5021964b88df1) in your local `bin` directory:

```shell
curl https://gist.githubusercontent.com/copycat-killer/76e315bc27c6cdf7edd5021964b88df1/raw/97f7ba586418a4e07637cfbc91d2974278dfa623/mpd-fade -o ~/bin/mpd-fade
```

Then, use a keybinding like this for toggling MPD:

```lua
    -- MPD toggle with volume fading
    awful.key({ altkey, "Control" }, "Up",
        function()
            awful.spawn.easy_async("mpc-fade 20 4",
            function(stdout, stderr, reason, exit_code)
                beautiful.mpd.update()
            end)
        end),
```

If you like this, I'll add it to the wiki.

Finally, as @Unode pointed, `mpc` allows crossfading between songs. Just read `man mpc`.

> Other thing I just recently asked myself, the project is called lain after Serial Experiments Lain anime?

`lain` is the acronym for Luke's [`vain`](https://github.com/vain/awesome-vain), which by chance is a reference to one of my favourite animes too. 😃

**Comment by Pablo1107** [comment]
Yes, thanks for replying men. This past days was exhausting to me.
Basically everything I did was a pain in the ass.

Hey, about the lain-vain reference, I though the same thing.
But I don't know. I think maybe it's a little bit ambiguous.

Can @copycat-killer just answer us? haha

I think people are a little bit "lunatic". lol

Cheers.

2017-02-26 10:37 GMT-03:00 Luke Bonham <notifications@github.com>:

**Comment by copycat-killer** [comment]
I'll take thas as a yes to my previous question:

> If you like this, I'll add it to the wiki.

**Comment by Pablo1107** [comment]
Thanks Luke, I supposed you liked my idea. When I have something to share,
never mind I will post it here.

See you later.

Pablo A. Dealbera

2017-02-28 6:50 GMT-03:00 Luke Bonham <notifications@github.com>:

**Comment by Pablo1107** [comment]
It's almost 2 years since I started this issue, but just recently I modify the script to make it work with my environment. 

```bash
curl https://gist.github.com/Pablo1107/1d61cfa39e683289d96301230bf88fa5 -o ~/bin/mpc-fade
chmod +x ~/bin/mpc-fade
```

The main difference is that volume always default to the current volume and reset volume after the fade out. Just need to figure out how to control only mpd volume. :)
