### ISSUE TITLE
Pulsebar widget, in line 51,  pulseaudio is a nil value.

### ISSUE THREAD

**Issue by haastt** [copycat-killer/lain#327]
Awesome -v:

```
awesome v4.0-221-g439d0c80-dirty (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```
Lua and LuaJit
`Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio`
`LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/`

In the Pulsebar widget line 51:
https://github.com/copycat-killer/lain/blob/master/widget/pulsebar.lua#L51
this pulseaudio variable is not defined anywhere before, and throws an error notification.

**Comment by copycat-killer** [comment]
Thanks.
