### ISSUE TITLE
Set layout for specific tag didn't work anymore

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#328]
Hi,

when using as the wiki said: awful.layout.set(lain.layout.termfair, tag)
This do not work.
error: attempt to index a number value (local 't')
PS my tag is: awful.util.tagnames = { "web", "c0de", "stuff", "RE", "VM" }

**Comment by copycat-killer** [comment]
Read [here](https://awesomewm.org/doc/api/libraries/awful.layout.html#set). 

If you want to use `awful.layout.set`, you have to specify the tag. For instance:

```lua
awful.layout.set(lain.layout.termfair, screen[1].tags[1]) -- set termfair on tag 1 of screen 1
```

**Comment by dummys** [comment]
oh,  thanks.

**Comment by dummys** [comment]
Still not working: awful.layout.set(lain.layout.termfair, screen[1].tags[1])
Got: attempt to index a nil value (local 't')

**Comment by copycat-killer** [comment]
You can also set it in the end of `rc.lua`.
