### ISSUE TITLE
Cpu widget is showing total used in percent rather than load average ?

### ISSUE THREAD

**Issue by dummys** [copycat-killer/lain#330]
During a makepkg -sri my htop shows this: 
![2017-03-03-22 25 45](https://cloud.githubusercontent.com/assets/1941445/23569856/ce671b28-0061-11e7-9ca6-ce22f4fdea8b.png)

It's not possible to show the total of all core in percentage rather than the Load average ?

**Comment by copycat-killer** [comment]
[Yes](https://github.com/copycat-killer/lain/wiki/cpu).

```lua
local cpu = lain.widget.cpu({
    settings = function()
        widget:set_markup(markup.font(theme.font, markup(gray, " Cpu ") .. cpu_now.usage .. " "))
    end
})
```

This one was easily answered by reading the wiki. Please, read the issue template next time.
