### ISSUE TITLE
Notification title of alsabar widget seems not right

### ISSUE THREAD

**Issue by Universebenzene** [copycat-killer/lain#345]
After recent update, the notifcation title of alsabar widget always appear as "Master - Muted" no matter whether the Master channel is muted or not. I just try the alsabar widget, and I'm not sure whether other volume widget have this problem or not. Are there any problem after the update of {alsa, pulse}bar?

**Comment by copycat-killer** [comment]
In ALSA, the flag `playback` equals to `not mute`, but I accidentally inverted. 

Thanks for the notification, it should be fixed now. 

> Are there any problem after the update of {alsa, pulse}bar?

I didn't touch anything else besides `{alsa, pulse}bar`.
