### ISSUE TITLE
bat's bat_notification_low_preset doesn't accept "preset" table?

### ISSUE THREAD

**Issue by sprnza** [copycat-killer/lain#347]
Hi there!
I'm trying to customize bat widget's notifications and find out that bat_notification_*_preset tables don't accept "preset" to be set to naughty.config.defaults.critical for example? Is it a bug or something?

**Comment by copycat-killer** [comment]
You're trying to use a table like a `naughty.notify` call, it doesn't work like that.

You just have to modify `bat_notification_*_preset` within `bat.update()`. For instance:

```lua
-- Battery
local bat = lain.widget.bat({
    settings = function()
        bat_notification_critical_preset.title = "A title I like more"
        bat_notification_critical_preset.text = "A text I like more"
        -- OR
        bat_notification_critical_preset = custom_table_with_same_fields
        -- [...]
    end
})
```

FYI, [`naughty.config.presets.critical`](https://awesomewm.org/doc/api/libraries/naughty.html#config.presets) colours are identical to [`bat_notification_critical_preset`](https://github.com/copycat-killer/lain/wiki/bat).

**Comment by sprnza** [comment]
Hi @copycat-killer !
Thanks! 

But:
> FYI, naughty.config.presets.critical colours are identical to bat_notification_critical_preset ones.

Nope, they aren't. `bat_notification_ctitical` is black and white, `'bat_notification_low_preset` is black and grey.
