### ISSUE TITLE
Taskwarrior widget does not show `task next` output on ubuntu

### ISSUE THREAD

**Issue by ionsquare** [copycat-killer/lain#348]
* output of `awesome -v` and `lua -v`

    ```bash
    $ awesome -v
    awesome v4.1 (Technologic)
     • Compiled against Lua 5.1.5 (running with Lua 5.1)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.4
     • LGI version: 0.9.0
    $ lua -v
    Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
    ```

* expected behavior and actual behavior
    * Expected: When hovering mouse over the taskwarrior widget, the icon, command text of "task next", and the output of the command should be displayed.
    * Actual: Icon and text "task next" are displayed correctly, but no tasks are listed.

* steps to reproduce the problem
    1. Install clean awesome-copycats by cloning repo according to installation instructions
    2. Switch theme to powerarrow
    3. Hover mouse over task widget

* other notes
    * If I type `task next` in a terminal, the tasks are displayed correctly.
    * If I edit `lain/widget/contrib/task.lua` and change task.show_cmd to `screenfetch`, then hovering over the widget icon correctly shows command output.
    * I have tried changing show_cmd to `/usr/bin/task next` as well, still nothing is displayed.
    * It works fine on my arch linux desktop, but not on my ubuntu laptop.
    * I have tried reinstalling task, did not help.

I use taskwarrior a lot, I'd really like to get this widget working and would appreciate any tips for figuring out what I'm doing wrong.

**Comment by copycat-killer** [comment]
On your Ubuntu laptop, get the output of

```shell
$ which task
```
and try setting it as `show_cmd` table argument in `task` widget [here](https://github.com/copycat-killer/awesome-copycats/blob/master/themes/powerarrow/theme.lua#L122). Example:

```lua
lain.widget.contrib.task.attach(task, {show_cmd = "/path/to/ubuntu/task"})
```

**Comment by ionsquare** [comment]
To make things even stranger, if I change show_cmd to "task add 'testing'", when I hover over the widget it shows "Created task 30", and if I hover over again, "Created task 31". So it is definitely calling the task command correctly, it's just not showing the output from 'task next' correctly. Maybe the colours or text formatting are screwing things up?

**Comment by copycat-killer** [comment]
See if Ubuntu likes this one:

```lua
lain.widget.contrib.task.attach(task, {
    show_cmd = "/usr/bin/task | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g'"
})
```

Be sure to use GNU `sed`.

**Comment by ionsquare** [comment]
Still no luck unfortunately. I used gnu sed and updated to the latest commit. Title now remains "task next" (I see that was one of the recent changes), and I'm thinking it might not be from the colours since I can use `screenfetch` as the command and that works fine, it just displays glyphs where the colour codes would be:

![screenfetch](https://user-images.githubusercontent.com/11220399/28272972-e372e95a-6ac1-11e7-85cb-f2739dc05355.png)

**Comment by copycat-killer** [comment]
Then wipe away Ubuntu! 😈 

Seriously speaking, try to start X like this:

```shell
startx -- -keeptty -nolisten tcp > $HOME/.xorg.log 2>&1
```

and check `~/.xorg.log` after hovering the mouse on the widget to see if it awesome output some `stderr`.

**Comment by duckwork** [comment]
I'm not sure if this is the right place to put this, but I was having the same problem today.  I solved it by changing my `show_cmd`:

    lain.widget.contrib.task.attach(task, {
        show_cmd = 'task rc.verbose:label'
    })

At first, I thought `rc.color` was causing the problem, but it was not; `rc.verbose` in the default setting is, I guess, setting some arcane terminal escape code.  `rc.verbose` also works with `nothing`, but I didn't try all the other settings available.

FYI, I'm using awesome v4.2 and task v2.5.1 on Gentoo.  I hope this points you in the right direction!

**Comment by ionsquare** [comment]
Awesome! That fixed it for me too.

**Comment by copycat-killer** [comment]
@duckwork Thank you, I'll update the wiki.
