### ISSUE TITLE
Calendar widget day highlight

### ISSUE THREAD

**Issue by seregaxvm** [copycat-killer/lain#350]
Calendar widget day highlight is not represented properly (see figure)

![calendar](https://user-images.githubusercontent.com/26824900/28287029-dc1fd786-6b42-11e7-88a0-1205892243d3.png)

I use `awesome-copycats` theme `Steamburn`. This is widget setup code:
```
lain.widget.calendar({
   attach_to = { mytextclock },
   cal = "/usr/bin/cal",
   notification_preset = {
       font = "Monospace 11",
       fg   = theme.fg_normal,
       bg   = theme.bg_normal
   }
})
```

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

Linux 4.9.0-3-amd64 Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

**Comment by copycat-killer** [comment]
https://github.com/copycat-killer/awesome-copycats/issues/190
https://github.com/copycat-killer/awesome-copycats/issues/186
