### ISSUE TITLE
Some widgets don't have an option to disable mouseover popup windows

### ISSUE THREAD

**Issue by gvlasov** [copycat-killer/lain#353]
Same as #352 

For me personally, the calendar widget needs the popups disabled, but it is probably a good idea to add the option for all the other widgets as well.

**Comment by copycat-killer** [comment]
> For me personally, the calendar widget needs the popups disabled

What's the point in having it, then? If you meant hovering popup, then see #320.

I added `notify` option to IMAP widget. Please list these other "some" widgets you are referring to.
