### ISSUE TITLE
Module 'lain.widget.watch' not found

### ISSUE THREAD

**Issue by vimalloc** [copycat-killer/lain#363]
When trying to start awesomewm (with the newest version of awesomewm and the newest lain AUR package installed), I'm now getting the following error:

```
/usr/share/awesome/lib/lain/helpers.lua:28: module 'lain.widget.watch' not found 
```
followed by a big list of files searched.

Was this changed again? I remember somewhat recently having to change it from abase to watch (iirc). Is there a change log I could follow that details these changes, so that my desktop doesn't stop working on reboot?

Thanks!

```
$ awesome -v
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

```
$ lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
```

**Comment by copycat-killer** [comment]
> Is there a change log I could follow that details these changes, so that my desktop doesn't stop working on reboot?

You can get it with `git log` or reading [here](https://github.com/copycat-killer/lain/commits/master).

I also report breaking changes in the [AUR comments](https://aur.archlinux.org/packages/lain-git/?comments=all). You can read there about your question.

Moreover, the AUR package is a git too, and it has the same log.

You can read the wiki as well, which is always up to date and reflects the repository status.

You have a lot of quick options, and a git version is unstable by definition, so there's little to blame.

But here's good news: a first stable release [has been planned](https://github.com/copycat-killer/lain/milestone/4), and I hope to do it ASAP.
