### ISSUE TITLE
Useless gaps don't work with mouse resize in Awesome stable branch

### ISSUE THREAD

**Issue by akdor1154** [copycat-killer/lain#48]
in the default tiling layouts, (awesome 3.4), modkey+rmb will resize whatever client is under the cursur and slide the layout divisions around accordingly. uselesstile doesn't do this. :(

**Comment by Alittlemurkling** [comment]
@akdor1154 I'm a bit impatient for this feature and would like to apply your patch. However, after adding the appropriate lines, I get: 
/usr/share/awesome/lib/awful/mouse/init.lua:570: attempt to index a nil value (global 'lain'). 
How did you properly include lain? Awesome fails to start when I write local lain = require("lain") at the top of the file. (I have it installed in $HOME/.config/awesome/lain)

**Comment by copycat-killer** [comment]
@Alittlemurkling check #87

**Comment by Alittlemurkling** [comment]
Oh, excellent. Sorry for missing that.

**Comment by copycat-killer** [comment]
In the new awesome 4.0, we have both the useless gaps feature and the above pull request merged. Closing.
