### ISSUE TITLE
I can't get the mpd widget working properly (and/or guidance needed).

### ISSUE THREAD

**Issue by rigoletto-dev** [copycat-killer/lain#526]
```
awesome devel (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
`Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio`

FreeBSD 13.0-RELEASE

**OBS. also tested against Lua 5.3, same behavior.**

**Disclamer:** I'm new to AwesomeWM and am know little to nothing about Lua.

1- adding local `local mympd = lain.widget.mpd()` alone works in a sense the notification appear but not the cover art, and this is important to not the music is archived in `~/Music` and `mpd` actually listen to 10.0.0.10 but when setting: `local mympd = lain.widget.mpd({host = "10.0.0.10"})` the result is the same except the notification never disappear.

[Config.](https://gitlab.com/rigoletto/awesome-files/-/blob/main/extras/statusbar.lua#L7-8)

2- adding [this](https://github.com/lcpz/awesome-copycats/blob/master/themes/blackburn/theme.lua#L117-L134) mpd widget example (and also to Wibar [config](https://gitlab.com/rigoletto/awesome-files/-/blob/main/extras/statusbar.lua#L134)) does nothing, nothing showup.

[Config](https://gitlab.com/rigoletto/awesome-files/-/blob/main/themes/theme.lua#L119-137)

PS. no Xorg errors.

Thank you.

**Comment by lcpz** [comment]
Replace [this line](https://gitlab.com/rigoletto/awesome-files/-/blob/main/extras/statusbar.lua#L134) with `mympd.widget`, and read the [wiki](https://github.com/lcpz/lain/wiki/mpd) to know how to make customizations.

For instance,  to set your music folder:

```lua
-- in your statusbar.lua

local lain = require("lain")
local markup = lain.util.markup

local mympd = lain.widget.mpd {
    music_dir = "/path/to/your/music/directory", -- change here
    settings = function()
        mpd_notification_preset.fg = "#FFFFFF"
        artist = mpd_now.artist .. " "
        title  = mpd_now.title  .. " "

        if mpd_now.state == "pause" then
            artist = "mpd "
            title  = "paused "
        elseif mpd_now.state == "stop" then
            artist = ""
            title  = ""
        end

        widget:set_markup(markup.font(theme.font, markup("#9E9C9A", artist) .. title .. " "))
    end
}
```

**Comment by rigoletto-freebsd** [comment]
Hello,

I changed `mympd` to `mympd.widget` but no difference, the widget doesn't show up. The music directory is the default so no need to change but I did it anyway to test (reinforce), and also used the example to set `host` correctly and again, the notification is persistent and without the album cover.

Btw, just to confirm all albums have a cover.jpg file in it.

Thank you.

**Comment by lcpz** [comment]
Naive questions: do you see "N/A N/A" in the top left-hand corner? When you launch MPD, does the widget update, or does the notification appear?

Try using [this](https://pastebin.com/ccbnCkVC) as your `~/.config/awesome.rc.lua`. Do you see "mpd off" in the top right-hand corner?

**Comment by lcpz** [comment]
Try removing lines 585 and 586. If you still have errors, just apply the same modification to the default `rc.lua` under FreeBSD. That is, just add the lines 21, 107-129, 236. What does the notification say? Is it empty? Are you sure your MPD is configured correctly?

**Comment by rigoletto-freebsd** [comment]
The notification display the expected information except by the album cover. This MPD configuration is in place since 2016 with minor changes of the times, I suppose everything is correct.

[musicpd.conf.txt](https://github.com/lcpz/lain/files/8345120/musicpd.conf.txt)

I will be able to try the provided configuration again soon.

Thank you.

**Comment by rigoletto-freebsd** [comment]
For the record,for comparative means, the 'Polybar' mpd module works as expected.

**Comment by rigoletto-freebsd** [comment]
I tried commenting the lines with error (585 and 586) and the widget appeared but as `mpd off` but the information was not updated, ever when changing tracks. Also, the notification worked but again without the cover art.

Thanks.

**Comment by lcpz** [comment]
> the notification worked but again without the cover art

Do you mean that it displayed the text *Now playing...*?

With MPD on, can you run this command and get the information without issues?

```shell
printf "status\ncurrentsong\nclose\n" | curl --connect-timeout 1 -fsm 3 telnet://127.0.0.1:6600
```

If this exact command does not work, play around with `curl` and see how can you make it work.

**Comment by rigoletto-freebsd** [comment]
With `telnet://127.0.0.1:6600` show nothing. but changing to telnet://10.0.0.10:6600 worked.

**Maybe a image is better.**
![screenshot_1648158037](https://user-images.githubusercontent.com/43918328/160014986-dc715027-40ae-4159-8f72-ff0f645b8ebd.png)

Thanks!

**Comment by rigoletto-freebsd** [comment]
I have not tested it but it seems the `vicious` mpd widget works.

**Comment by lcpz** [comment]
Did you try setting your host? Continuing with the above example:

```lua
-- in your statusbar.lua

local lain = require("lain")
local markup = lain.util.markup

local mympd = lain.widget.mpd {
    host = "10.0.0.10", -- <--
    settings = function()
        mpd_notification_preset.fg = "#FFFFFF"
        artist = mpd_now.artist .. " "
        title  = mpd_now.title  .. " "

        if mpd_now.state == "pause" then
            artist = "mpd "
            title  = "paused "
        elseif mpd_now.state == "stop" then
            artist = ""
            title  = ""
        end

        widget:set_markup(markup.font(theme.font, markup("#9E9C9A", artist) .. title .. " "))
    end
}
```

**Comment by rigoletto-freebsd** [comment]
Yes, but when I set it the only change is the notification that doesn't disappear anymore. If I click on it disappear but after a moment it appear again - _pretty weird_.

Thank you!

**Comment by lcpz** [comment]
The only thing that comes to my mind is to start with a default `rc.lua` and a minimal `lain` configuration, like [this one](https://pastebin.com/UxwBhj0i), and try it to debug it yourself by [checking X's stdout for errors](https://github.com/lcpz/lain/blob/master/ISSUE_TEMPLATE.md#how-to-provide-x-error-log).

**Comment by rigoletto-freebsd** [comment]
One thing that came to mind now is `mpd` is called `musicpd` on FreeBSD (due to conflict with something in FreeBSD Base).

**Comment by lcpz** [comment]
This is not important, as we connect to the service's address:port. When you can, check X logs as I mentioned above.

**Comment by rigoletto-freebsd** [comment]
Don't ask me how but I managed to have some progress. :-D

Now the widget appear and work nicely provided `host` is set correctly (otherwise `mpd off`); however the notification refuse to disappear unless `host` is set to default. In any circumstance no cover art in the notification.

Thank you.

**Comment by lcpz** [comment]
In your `xorg.log`, you have a lot of these errors:

```shell
E: awesome: Failed to load 'inactive': Failed to open file “inactive”: No such file or directory
E: awesome: Failed to load '': Failed to open file “”: No such file or directory
```

Last step: `cd` to a music folder with a cover image file, and run this command:

```shell
find . -maxdepth 1 -type f | egrep -i m1 '*\.(jpg|jpeg|png|gif)$'
```

Modify it until it returns the image file (e.g., `cover.jpg`). Then, use the last argument of the above command (escaping it in Lua format). Example:

```lua
local lain = require("lain")
local markup = lain.util.markup

local mympd = lain.widget.mpd {
    cover_pattern = "*\\.(jpg|jpeg|png|gif)$", -- modify accordingly, remember to escaping it
    settings = function()
        mpd_notification_preset.fg = "#FFFFFF"
        artist = mpd_now.artist .. " "
        title  = mpd_now.title  .. " "

        if mpd_now.state == "pause" then
            artist = "mpd "
            title  = "paused "
        elseif mpd_now.state == "stop" then
            artist = ""
            title  = ""
        end

        widget:set_markup(markup.font(theme.font, markup("#9E9C9A", artist) .. title .. " "))
    end
}```

**Comment by rigoletto-freebsd** [comment]
Wow, that did the trick: `"\.(jpg|jpeg|png|gif)$"`. Albeit there two issues:

1 - `host` need to be set explicit (127.0.0.1) otherwise the cover art doesn't show up.
2 - it needs to be `127.0.0.1` (not tested `localhost`) otherwise the notification doesn't disappear. ^^

Thank you.

**Comment by lcpz** [comment]
We solved it, then? If so, please close the issue. Otherwise, please let me how can I help you further.
