### ISSUE TITLE
lain imap widget doesn't work  with gmail

### ISSUE THREAD

**Issue by osleg** [copycat-killer/lain#74]
Hey,
Trying to make mailwidget working with gmail account, here my settings:

```
    timeout  = 380,
    is_plain = true,
    server   = "imap.gmail.com",
    mail     = "alex@wall-dev.org",
    password = "mypa$$w0rdh3r3",
```

Sent myself an email, i can see it in inbox and it 100% unread but i never get the mail notification widget showing up.

**Comment by vevais** [comment]
Hello! I am having the same problem as OP. Is there a fix for this by now?

**Comment by copycat-killer** [comment]
If you have a mail password with spaces, then yes, there is.

**Comment by vevais** [comment]
My password does not contain any spaces.

**Comment by copycat-killer** [comment]
`git pull` latest lain commit, read the [wiki](https://github.com/copycat-killer/lain/wiki/imap) and do a correct setup.

If you're still having issues after these steps, email me or open a new issue here.
