### ISSUE TITLE
bat.lua:33: attempt to index field 'widget' (a nil value)

### ISSUE THREAD

**Issue by Bew78LesellB** [copycat-killer/lain#80]
Hello,

I have a problem when using your module : 
![capt](https://cloud.githubusercontent.com/assets/9730330/5429140/2ed179e0-83e1-11e4-9712-f3cf06747187.png)

what can I do for that ?

PS: I've found: I have awesome 3.4 and not 3.5..
and I can't install the 3.5 :(

**Comment by copycat-killer** [comment]
You have all the information you need. 

Of course, feel free to ask me for further help.

Closing.
