### ISSUE TITLE
attempt to call field 'alsa' (a table value)

### ISSUE THREAD

**Issue by AnderRasoVazquez** [copycat-killer/lain#81]
I tried to create a volume widget using this code:
```lua
volumewidget = lain.widgets.alsa({
        timeout = 0.5,
        settings = function ()
            widget:set_markup("<span color='#db2bff'>[ sound ] " .. volume_now.level .. " " .. volume_now.status .. "</span>")
        end
    })
```
But I get an error:
```
attempt to call field 'alsa' (a table value)
```
It's strange because I used this code some months ago and it worked.

**Comment by copycat-killer** [comment]
I loaded your `rc.lua` and had no trouble with it. The module works.

<a href="http://imgur.com/hvDXURH"><img src="http://i.imgur.com/hvDXURH.png" title="source: imgur.com" /></a>

I can only suggest you to update Awesome, Lua and Lain. And also to organize better your code.

Closing.
