### ISSUE TITLE
temp widget false value with lm sensors with AMD Phenom X4 9550 on A7GM-S 2.0

### ISSUE THREAD

**Issue by qubodup** [copycat-killer/lain#84]
Hello, thank you for lain and awesome-copycats!

On Arch Linux with AMD Phenom X4 9550 on A7GM-S 2.0, https://github.com/copycat-killer/lain/wiki/temp uses /sys/devices/virtual/thermal/thermal_zone0/temp which always contains the value 40000.

using `find /sys/devices/ -name "*temp*"` I discovered another file, which seems to contain a correct value (analog to `sensors`), which gets updated:
/sys/devices/pci0000:00/0000:00:18.3/temp1_input

I'm not sure what causes the first file not being updated or how to tell which file should be used to get the updated temperature.

As a dirty fix, I edit /usr/share/awesome/lib/lain/widgets/temp.lua and replace the imported files, hoping it will stay the same after rebooting.

**Comment by qubodup** [comment]
Just a quick update. In my case (arch linux upgrade), the temperature file recently moved to:

  /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon0/temp1_input

For a while i just saw "N/A°C". Remember to use the following command to find your tempereature file(s?):

  find /sys/devices/ -name "*temp*"

**Comment by copycat-killer** [comment]
Added to the [wiki](https://github.com/copycat-killer/lain/wiki/temp).

**Comment by cr4i50n** [comment]
I wonder why editing library code (/usr/share/awesome/lib/lain/widgets/temp.lua) does not provide the same satisfiable result as adding an argument to rc.lua  i.e. modifiyng widget input table as copycat-killer recommended :

 tempwidget = lain.widgets.temp({
    tempfile = "/path/to/my/right/file",
    settings = function()
        widget:set_text(coretemp_now)
    end
})

anyway, this seems to be working for me only if adding the additional argument to the widget definition table (rc.lua).
Arch Linux last upgrade here.

thank you both qubodup, copycat-killer.
