### ISSUE TITLE
mem used frozen, swapused jumping

### ISSUE THREAD

**Issue by qubodup** [copycat-killer/lain#85]
Hi,

With my current setup, often the mem widget displaying mem_now.used value freezes and instead mem_now.swapused flashes during the update step, showing the current mem_now.used value, for some reason in the color (markup) of the mem widget.

Video:
http://youtu.be/YRNpK-6pgJg
Note: the flashing yellow value does change, although it's not identical to htop. In the video it's 1317 at first, changes to values like 1310, 1311 later, while the left constant yellow value stays the same, as it seems, the memused value when awesome starts/rc.lua runs.

Example screens:
![wat2](https://cloud.githubusercontent.com/assets/18312/5592768/1a8c0590-91e2-11e4-8ccb-16a0ceb2def0.png)
![wat](https://cloud.githubusercontent.com/assets/18312/5592767/1a8ad9ea-91e2-11e4-9573-9e484bed23b5.png)

rc.lua:
http://codepad.org/qICre4sQ

theme:
http://codepad.org/ysmWeejM

I think it has to do with using the mem widget twice. Perhaps because of non-local variables (entirely guessing) in https://github.com/copycat-killer/lain/blob/master/widgets/mem.lua

Is one supposed not to use a widget twice?

**Comment by copycat-killer** [comment]
Is one supposed not to use a widget twice?

Yes, this is the same as in #61. You're causing a race condition.

Rewrite your widgets like this:

```lua
-- memory/swap
memicon = wibox.widget.imagebox(beautiful.widget_mem)
swapicon = wibox.widget.imagebox(beautiful.widget_fs)
swapwidget = wibox.widget.textbox()
memwidget = lain.widgets.mem({
    timeout = 0.5,
    settings = function()
        widget:set_markup(markup("#e0da37", mem_now.used .. "MB "))
        swapwidget:set_markup(markup("#80d9d8", mem_now.swapused .. "MB "))
    end
})
```

It's easy to make the widget asynchronous, but I prefer not in order to avoid such bad habits.

**Comment by qubodup** [comment]
This solves it, thanks!
