### ISSUE TITLE
uselesstile with wider internal gaps behaves strange when using uselesstile.bottom/top

### ISSUE THREAD

**Issue by Xiaoming94** [copycat-killer/lain#92]
Well, easier showing with a screenshot: http://i.imgur.com/g4yK4sP.png

**Comment by copycat-killer** [comment]
Try [revision 3](https://gist.github.com/copycat-killer/9e56dcfbe66bfe14967c).

**Comment by Xiaoming94** [comment]
Works like a charm! Thanks!! :D
