### ISSUE TITLE
'Uselesstile code refactoring' commit breaks vertical client resizing

### ISSUE THREAD

**Issue by Chad-** [copycat-killer/lain#93]
Previously by setting these keys it was possible to adjust the height of clients:

    awful.key({ modkey, "Shift" }, "l", function () awful.client.incwfact(-0.05) end),
    awful.key({ modkey, "Shift" }, "h", function () awful.client.incwfact( 0.05) end),

Commit https://github.com/copycat-killer/lain/commit/192543618537de4a4dab3adc14ad4bd6d696304e has broken this functionality as it no longer uses `tag.getdata(t).windowfact`.

**Comment by copycat-killer** [comment]
The author is @worron , maybe he can propose a quick and good solution.

I'll give it a look later.

**Comment by copycat-killer** [comment]
Mh, didn't see that.

@worron is the author, maybe he can propose a quick solution.

I'll give it a look later.

#88

**Comment by worron** [comment]
My fault, totally missed it. Will try to fix.
