### ISSUE TITLE
Mpd widget issue

### ISSUE THREAD

**Issue by daaawx** [copycat-killer/lain#95]
I am having some trouble with the mpd.lua after setting up a copycat theme (https://github.com/copycat-killer/awesome-copycats), here is the error message:

Oops, an error happened!
/home/dax/.config/awesome/lain/widgets/mpd.lua:67 attempt to index local 'f' (a nil value)

**Comment by copycat-killer** [comment]
Is mpd set up properly?

And lain up-to-date? (`cd ~/.config/awesome/lain; git pull`)

If yes, link me your mpd configuration in `rc.lua`.

**Comment by copycat-killer** [comment]
So?

**Comment by daaawx** [comment]
Hello and sorry, i completely forgot about this thread! 

It was in fact a problem with lain, updating and restarting the computer solved the issue. Thank you.
