### ISSUE TITLE
net widget - show ip

### ISSUE THREAD

**Issue by r8b7xy** [copycat-killer/lain#99]
What would you say for support to show current ip?
It could be quite handy when using e.g. openvpn.

**Comment by copycat-killer** [comment]
I'd say: keep it simple and use [base](https://github.com/copycat-killer/lain/wiki/base) or [abase](https://github.com/copycat-killer/lain/wiki/abase) instead.

**Comment by copycat-killer** [comment]
But you can share your implementation in the wiki, if you like.
